<?php
/**
 * @version		$Id: controller.php 3 2015-06-02 09:43 phu $
 * @package		vFramework.contact
 * @copyright	(C) 2015 Vipcom. All rights reserved.
 * @license		Commercial
 */
defined('V_LIFE')or die('v');$tpl->lang('contact');function contact_controller($p=0,$b='form'){global $tpl,$mem,$alt,$db,$map,$cfg;if(!isset($mem))$mem=vSession::instance();$i=$mem->session('get','flc',2);if($p)$alt['module']=& $map->i[$p];else{$p=$map->r[$alt['page']]['id'];$alt['module']=& $map->r[$alt['page']];}$o=& $alt['module']['prop'];$s=vRequest::issubmit('submit');$e=0;$r=array();$f=array();$x=array();$m=array();$t=preg_split('/[\n,;]/',$o['ext']);foreach($t as $v){if($v){$v=preg_split('/[:=]/',$v.':');$f[($v[0]{0}=='~'||$v[0]{0}=='*'||$v[0]{0}=='#')?substr($v[0],1):$v[0]]=$v[1];if($v[0]{0}=='*'||$v[0]{0}=='#')$r[]=substr($v[0],1);}}unset($t);if($s){vRequest::vars($x,$f);foreach($f as $k=>$v){if(in_array($v,array('image','media','file'))){$k2=$k.'_uploader';if(isset($x[$k2])&&$x[$k2]&&!$x[$k2]['error']&&$x[$k2]['tmp_name']){require_once(PATH_CORE.DS.'file.php');if($a=vFilter::file($x[$k2]['name'],$v)){$a1=preg_replace('#\.[^.]*$#','',$a);$a2=substr(strrchr($a,'.'),1);if($a=$file->upload($x[$k2]['tmp_name'],'tmp/'.$a1.'_'.substr(md5($x[$k2]['tmp_name']),0,5).'.'.$a2))$x[$k]=$a;}}unset($x[$k2]);unset($k2);}else if(in_array($v,array('images','medias','files'))){$k2=$k.'_uploader';if(isset($x[$k2])&&$x[$k2]){for($i=0,$n=count($x[$k2]['tmp_name']);$i<$n;$i++){if(!$x[$k2]['error'][$i]&&$x[$k2]['tmp_name'][$i]){require_once(PATH_CORE.DS.'file.php');if($a=vFilter::file($x[$k2]['name'][$i],$v)){$a1=preg_replace('#\.[^.]*$#','',$a);$a2=substr(strrchr($a,'.'),1);if($a=$file->upload($x[$k2]['tmp_name'][$i],'tmp/'.$a1.'_'.substr(md5($x[$k2]['tmp_name'][$i]),0,5).'.'.$a2))$x[$k][$i]=$a;}}}}unset($x[$k2]);unset($k2);$x[$k]=implode("\n",$x[$k]);}}foreach($r as $k){if(!$x[$k]){$m[$k]='';$e++;}}if($i>1&&!vCaptcha::check(vRequest::string('captcha_sid'),vRequest::string('captcha'))){$m['captcha']='';$e++;}if($e==0){$sql=$db->sql('INSERT','#__contact',array('cid'=>$p,'title'=>((isset($o['eml'])&&$o['eml'])?$o['eml']:$alt['module']['title']),'prop'=>vRegistry::ini($x),'created'=>time(),'unread'=>1));if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if(isset($o['eml'])&&$o['eml']){$replyto='';$t='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head><body><table border="1" cellspacing="0" cellpadding="10"><tr><td>Date</td><td>'.date('r').'</td></tr>';foreach($x as $k=>$v){switch($f[$k]){case 'image':case 'media':case 'file':$v='<a href="'.vRequest::site().URL_UPLOAD.$v.'">'.$v.'</a>';break;case 'images':case 'medias':case 'files':$c='';foreach(explode("\n",$v)as $v)$c.='<p><a href="'.vRequest::site().URL_UPLOAD.$v.'">'.$v.'</a></p>';$v=$c;break;case 'category':case 'categoryr':if(!isset($c)){$c=array();$sql='SELECT prop FROM #__ctype WHERE ctype=2 AND name="category"';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);$cat=vRegistry::parse($db->fetch_field('prop'));}if(isset($cat[$k])){if(!isset($c[$k]))$c[$k]=new vCategory($k,1,$cat[$k][1],$cat[$k][2]);$v=$c[$k]->nav($v);}break;}$t.="\n".'<tr><td>'.ucfirst($k).'</td><td>'.$v.'</td></tr>';if(!$replyto&&($k=='email'||$f[$k]=='email'))$replyto=$x[$k];}$t.='</table></body></html>';$mailer=new vMailer();$mailer->from($cfg['email'],$cfg['site'])->replyto($replyto)->to($o['eml'])->subject('['.$cfg['site'].'] '.$tpl->l['RP_MAIL_TITLE'])->htmltype(true)->message($t)->send();}$i++;$mem->session('set','flc',$i);vPage::message($tpl->l['RP_CONTACT_SC']);$x=array();}else{$s=false;}}if($s===false){$h='';if($m){foreach($m as $k=>$v){$h.='$("#'.$k.'").addClass("error");';}$h='<script type="text/javascript">'.$h.'</script>';}$tpl->reset_block($b);$tpl->block($b,array('ROWS'=>vForm::draw($o['ext'],$x,null,$r).(($i>1)?vForm::draw(array('captcha'=>'captcha')):'').$h,));vPage::message($tpl->l[($e)?'ERR_CONTACT':'RP_CONTACT']);}}