<?php
/**
 * @category   PHPExcel
 * @package    PHPExcel_Cell
 * @copyright  Copyright (c) 2006 - 2012 PHPExcel (http://www.codeplex.com/PHPExcel)
 * @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version    1.7.7, 2012-05-19
 */
if(!defined('PHPEXCEL_ROOT')){define('PHPEXCEL_ROOT',dirname(__FILE__).'/../../');require(PHPEXCEL_ROOT.'PHPExcel/Autoloader.php');}
class PHPExcel_Cell_AdvancedValueBinder extends PHPExcel_Cell_DefaultValueBinder{public function bindValue(PHPExcel_Cell $cell,$value=null){if(is_string($value)){$value=PHPExcel_Shared_String::SanitizeUTF8($value);}$dataType=parent::dataTypeForValue($value);if($dataType===PHPExcel_Cell_DataType::TYPE_STRING&&!$value instanceof PHPExcel_RichText){if($value==PHPExcel_Calculation::getTRUE()){$cell->setValueExplicit(True,PHPExcel_Cell_DataType::TYPE_BOOL);return true;}elseif($value==PHPExcel_Calculation::getFALSE()){$cell->setValueExplicit(False,PHPExcel_Cell_DataType::TYPE_BOOL);return true;}if(preg_match('/^'.PHPExcel_Calculation::CALCULATION_REGEXP_NUMBER.'$/',$value)){$cell->setValueExplicit((float) $value,PHPExcel_Cell_DataType::TYPE_NUMERIC);return true;}if(preg_match('/^\-?[0-9]*\.?[0-9]*\s?\%$/',$value)){$cell->setValueExplicit((float)str_replace('%','',$value)/ 100,PHPExcel_Cell_DataType::TYPE_NUMERIC);$cell->getParent()->getStyle($cell->getCoordinate())->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_PERCENTAGE);return true;}if(preg_match('/^(\d|[0-1]\d|2[0-3]):[0-5]\d$/',$value)){list($h,$m)=explode(':',$value);$days=$h / 24 + $m / 1440;$cell->setValueExplicit($days,PHPExcel_Cell_DataType::TYPE_NUMERIC);$cell->getParent()->getStyle($cell->getCoordinate())->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_TIME3);return true;}if(preg_match('/^(\d|[0-1]\d|2[0-3]):[0-5]\d:[0-5]\d$/',$value)){list($h,$m,$s)=explode(':',$value);$days=$h / 24 + $m / 1440 + $s / 86400;$cell->setValueExplicit($days,PHPExcel_Cell_DataType::TYPE_NUMERIC);$cell->getParent()->getStyle($cell->getCoordinate())->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_TIME4);return true;}if(($d=PHPExcel_Shared_Date::stringToExcel($value))!==false){$cell->setValueExplicit($d,PHPExcel_Cell_DataType::TYPE_NUMERIC);if(strpos($value,':')!==false){$formatCode='yyyy-mm-dd h:mm';}else{$formatCode='yyyy-mm-dd';}$cell->getParent()->getStyle($cell->getCoordinate())->getNumberFormat()->setFormatCode($formatCode);return true;}if(strpos($value,"\n")!==false){$value=PHPExcel_Shared_String::SanitizeUTF8($value);$cell->setValueExplicit($value,PHPExcel_Cell_DataType::TYPE_STRING);$cell->getParent()->getStyle($cell->getCoordinate())->getAlignment()->setWrapText(true);return true;}}return parent::bindValue($cell,$value);}}