<?php
/**
 * @version		$Id: sitemap.php 3 2013-12-30 14:54 phu $
 * @package		vFramework.cp.sitemap
 * @copyright	(C) 2012 Vipcom. All rights reserved.
 * @license		Commercial
 */
defined('V_LIFE')or die('v');$cfg['file']['dir']='s';$cfg['paging']=100;$sitemap_cfg=array('structure'=>'id:int,sid:int;pid:page,title,alias:alias,ctype:ctype,pic_thumb:image,auth:int,prop:prop,tree:tree,meta:meta,count:int,ordering:int,enabled:int','trans'=>'title,alias,meta','langs'=>1,'task'=>array('index'=>array('type'=>4,'auth'=>'access','cmd'=>'create,delete,publish,resync,move,imexport','filter'=>'search,publish','field'=>'id,title,alias,ctype,pic_thumb,count,ordering,enabled','render'=>'title,alias,ctype,count,ordering',),'edit'=>array('type'=>12,'auth'=>'edit','field'=>'id,pid,title,alias,ctype,pic_thumb,auth,ordering,prop,meta,enabled','render'=>'pid,title,alias,ctype,pic_thumb,ordering','render2'=>'prop,meta','notnull'=>'title',),'prop'=>array(),'order'=>array('type'=>22,'auth'=>'move',),'resync'=>array('type'=>23,'field'=>'id,pid,tree,count,ctype,ordering',),'delete'=>array('type'=>11,'auth'=>'delete','ret'=>'',),'publish'=>array('type'=>21,'field'=>'enabled','auth'=>'publish','ret'=>'',),'move'=>array('auth'=>'delete','ret'=>'',),'imexport'=>array('type'=>31,'field'=>'id,pid,title,alias,ctype,auth,prop,meta,ordering','render'=>'meta','auth'=>'admin','paging'=>9999,),),'url'=>'','cfg'=>'','msg'=>array(0),);
class Sitemap extends vCPController{public function __construct(){if(V_LIFE==2)$this->model=new SitemapModel();parent::__construct();}protected function index_data($d=null){global $map,$stf,$ctype;$d=parent::data($d);for($i=0,$n=count($d);$i<$n;$i++){$v=&$d[$i];$v['CSS'].=' step'.$map->i[$v['id']]['tree']['l'];$v['U_VIEW']=(isset($ctype->r[0][$v['ctype']])&&$ctype->r[0][$v['ctype']]['func']&&$stf->auth($v['id'],'access'))?VAR_INDEX.'?'.VAR_LANG.'='.vPage::alt('lang').'&amp;'.VAR_PAGE.'='.$map->i[$v['id']]['alias']:'';}return $d;}protected function edit_data($d=0){global $cfg,$tpl,$map;if(!$d)$d=array('ctype'=>'null','prop'=>null,'meta'=>null,'auth'=>0,'enabled'=>1);vPage::head('<script type="text/javascript">$(function() {
$("#ctype").parent().append(\'<p><input type="checkbox" name="applyp" id="applyp" value="1" {edit.APPLYP}><label for="applyp">'.$tpl->l['APPLYP'].'</label></p><p><input type="checkbox" name="applyc" id="applyc" value="1" {edit.APPLYC}><label for="applyc">'.$tpl->l['APPLYC'].'</label></p>\');
propsw();
function propsw(){
	if ($("#applyp:checked").val() == 1) $("#prop").hide();
	else if($("#prop").html()) $("#prop").show();
}
$("#applyp").change(function(){propsw();});
$("input#ordering").parent().parent().hide();
})</script>');if($map->m){$this->cfg['task']['edit']['render'][]='auth';$d['auth']=vForm::select(array(0=>$tpl->l['MEMBER'].' + '.$tpl->l['GUEST'],1=>$tpl->l['MEMBER']),'auth','','','',$d['auth']);}return parent::data($d);}protected function request(){global $map;$x=parent::request();if(vRequest::bool('applyp')&&$x['pid']&&$x['ctype']==$map->i[$x['pid']]['ctype'])$x['prop']=vRegistry::ini($map->i[$x['pid']]['prop']);if(V_LIFE==2&&!isset($x['sid']))$x['sid']=V_SITE;return $x;}protected function submit($d){global $map,$db;$a=parent::submit($d);if($a&&vRequest::bool('applyc')){if($map->i[$d['id']]['tree']['f']){$t=explode(',',$map->i[$d['id']]['tree']['f']);for($i=0,$j=sizeof($t);$i<$j;$i++){if($d['ctype']!=$map->i[$t[$i]]['ctype'])unset($t[$i]);}if($t){$sql='UPDATE #__sitemap SET prop="'.$d['prop'].'" WHERE id IN ('.implode(',',$t).')';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);}}}return $a;}protected function delete_task(){global $map,$tpl;$id=vRequest::arr('ids','int');if($id){$a=array();foreach($id as $v){if($map->i[$v]['count']==0&&$map->i[$v]['tree']['c']==''){$a[]=$v;}}vRequest::set('ids',$a);parent::task();if(count($a)!=count($id)){$this->cfg['msg'][0]=1;$this->cfg['msg'][]=$tpl->l['ERR_DEL_EMPTY'];}}}protected function move_task(){global $map,$ctype,$tpl,$db;$a=0;$i=vRequest::arr('ids','int');$f=vRequest::int('from');$s='';if(is_array($i)){if($f&&isset($map->i[$f])){$s=$map->i[$f]['ctype'];}else{$f='';$s=array_shift($i);array_unshift($i,$s);$s=isset($map->i[$s])?$map->i[$s]['ctype']:'';}}if($s&&$ctype->r[0][$s]['func']==0)$s='';if($s==''){vPage::redirect($this->cfg['url']);return;}if(vRequest::int('update')){$t=vRequest::int('to');if(isset($map->i[$t])){if($f)$sql='UPDATE #__'.$s.' SET cid='.$t.' WHERE id IN ('.implode(',',$i).')';else $sql='UPDATE #__'.$s.' SET cid='.$t.' WHERE cid IN ('.implode(',',$i).')';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);cpPage::report('RP_MOVE');if(isset($this->cfg['type'][23])){vPage::alt('task',$this->cfg['type'][23]);$this->call($this,'task');}$this->ret=1;}}else{$t=$map->select();foreach($t as $k=>$v){if($map->i[$k]['ctype']!=$s)unset($t[$k]);}cpPage::nav('Move');cpPage::cmd('update');cpPage::cmd('cancel',$this->cfg['url']);$h='<form id="main_form" name="main_form" method="POST" action="'.$this->cfg['url'].'&amp;'.VAR_TASK.'=move&amp;from='.$f.'">
<input type="hidden" name="update" value="1" /><input type="submit" class="hidden" name="s'.time().'" value="" />
<table class="form_wra"><tbody><tr><td class="td_wra"><table class="form"><tr><th>'.$tpl->_('Posts').'</th><td>';if($f){$sql='SELECT id, title FROM #__'.$s.' WHERE id IN ('.implode(',',$i).')';if($db->query($sql)){$i=$db->fetch();foreach($i as $k)$h.='<p><input type="checkbox" name="ids['.$k['id'].']" id="r'.$k['id'].'" value="'.$k['id'].'" checked="checked" /><label for="r'.$k['id'].'">'.$k['title'].'</label></p>';}}else{foreach($i as $k)$h.='<p><input type="checkbox" name="ids['.$k.']" id="r'.$k.'" value="'.$k.'" checked="checked" /><label for="r'.$k.'">'.$map->i[$k]['title'].' ('.$map->i[$k]['count'].')</label></p>';}$h.='</td></tr>
<tr><th>'.$tpl->_('Move to').'</th><td>'.vForm::select($t,'to').'</td></tr>
</table></td></tr></tbody></table></form>';$tpl->theme('body','',$h);}}}if(V_LIFE==2){
class SitemapModel extends vCPModel{protected function records_sql($a=0){$s=parent::records_sql($a);$s['w'].=' AND a.sid='.V_SITE;return $s;}protected function erecords_sql($a=0,$b=0,$r=1){$s=parent::erecords_sql($a,$b,$r);$s[0]['w'].=' AND sid='.V_SITE;return $s;}}}$ctrl=new Sitemap();$ctrl->exec();unset($ctrl);