/* Functions */
Array.prototype.ex_file=function(a){for(i in a)for(var b=-1;-1<(b=this.indexOf(a[i]));)this.splice(b,1)};function replace_file(a,b,d){for(var c=0;c<a.length;c++)a[c]==b&&a.splice(c,1,d)};

/* Crop */
(function(g){g.Jcrop=function(p,J){function q(a){return parseInt(a,10)+"px"}function A(a){return parseInt(a,10)+"%"}function K(a){a=g(a).offset();return[a.left,a.top]}function B(a){return[a.pageX-P[0],a.pageY-P[1]]}function E(a){"object"!==typeof a&&(a={});b=g.extend(b,a);"function"!==typeof b.onChange&&(b.onChange=function(){});"function"!==typeof b.onSelect&&(b.onSelect=function(){});"function"!==typeof b.onRelease&&(b.onRelease=function(){})}function ba(a,b){P=K(l);C.setCursor("move"===a?a:a+"-resize");
if("move"===a)return C.activateHandlers(oa(b),W);var r=t.getFixed(),j=ca(a),c=t.getCorner(ca(j));t.setPressed(t.getCorner(j));t.setCurrent(c);C.activateHandlers(pa(a,r),W)}function pa(a,e){return function(r){if(b.aspectRatio)switch(a){case "e":r[1]=e.y+1;break;case "w":r[1]=e.y+1;break;case "n":r[0]=e.x+1;break;case "s":r[0]=e.x+1}else switch(a){case "e":r[1]=e.y2;break;case "w":r[1]=e.y2;break;case "n":r[0]=e.x2;break;case "s":r[0]=e.x2}t.setCurrent(r);m.update()}}function oa(a){var b=a;X.watchKeys();
return function(a){t.moveOffset([a[0]-b[0],a[1]-b[1]]);b=a;m.update()}}function ca(a){switch(a){case "n":return"sw";case "s":return"nw";case "e":return"nw";case "w":return"ne";case "ne":return"sw";case "nw":return"se";case "se":return"nw";case "sw":return"ne"}}function da(a){return function(e){if(b.disabled||"move"===a&&!b.allowMove)return!1;L=!0;ba(a,B(e));e.stopPropagation();e.preventDefault();return!1}}function ea(a,b,r){var j=a.width(),c=a.height();j>b&&0<b&&(j=b,c=b/a.width()*a.height());c>r&&
0<r&&(c=r,j=r/a.height()*a.width());u=a.width()/j;z=a.height()/c;a.width(j).height(c)}function Y(a){return{x:parseInt(a.x*u,10),y:parseInt(a.y*z,10),x2:parseInt(a.x2*u,10),y2:parseInt(a.y2*z,10),w:parseInt(a.w*u,10),h:parseInt(a.h*z,10)}}function W(){var a=t.getFixed();a.w>b.minSelect[0]&&a.h>b.minSelect[1]?(m.enableHandles(),m.done()):m.release();C.setCursor(b.allowSelect?"crosshair":"default")}function fa(a){if(b.disabled||!b.allowSelect)return!1;L=!0;P=K(l);m.disableHandles();"crosshair"!==ga&&
(C.setCursor("crosshair"),ga="crosshair");var e=B(a);t.setPressed(e);m.update();C.activateHandlers(qa,W);X.watchKeys();a.stopPropagation();a.preventDefault();return!1}function qa(a){t.setCurrent(a);m.update()}function ha(){var a=g("<div></div>").addClass(b.baseClass+"-tracker");g.browser.msie&&a.css({opacity:0,backgroundColor:"white"});return a}function ia(a){ja([parseInt(a[0],10)/u,parseInt(a[1],10)/z,parseInt(a[2],10)/u,parseInt(a[3],10)/z])}function ja(a){t.setPressed([a[0],a[1]]);t.setCurrent([a[2],
a[3]]);m.update()}function ka(){b.disabled=!0;m.disableHandles();m.setCursor("default");C.setCursor("default")}function la(){b.disabled=!1;Z()}function Z(a){b.allowResize?a?m.enableOnly():m.enableHandles():m.disableHandles();C.setCursor(b.allowSelect?"crosshair":"default");m.setCursor(b.allowMove?"move":"default");b.hasOwnProperty("setSelect")&&(ia(b.setSelect),m.done(),delete b.setSelect);b.hasOwnProperty("trueSize")&&(u=b.trueSize[0]/s,z=b.trueSize[1]/o);b.hasOwnProperty("bgColor")&&(g.fx.step.hasOwnProperty("backgroundColor")&&
b.fadeTime?D.animate({backgroundColor:b.bgColor},{queue:!1,duration:b.fadeTime}):D.css("backgroundColor",b.bgColor),delete b.bgColor);b.hasOwnProperty("bgOpacity")&&(U=b.bgOpacity,m.isAwake()&&(b.fadeTime?l.fadeTo(b.fadeTime,U):D.css("opacity",b.opacity)),delete b.bgOpacity);Q=b.maxSize[0]||0;R=b.maxSize[1]||0;S=b.minSize[0]||0;T=b.minSize[1]||0;b.hasOwnProperty("outerImage")&&(l.attr("src",b.outerImage),delete b.outerImage);m.refresh()}var b=g.extend({},g.Jcrop.defaults),P,ga,$=!1;g.browser.msie&&
"6"===g.browser.version.split(".")[0]&&($=!0);"object"!==typeof p&&(p=g(p)[0]);"object"!==typeof J&&(J={});E(J);var ma={border:"none",margin:0,padding:0,position:"absolute"},F=g(p),l=F.clone().removeAttr("id").css(ma);l.width(F.width());l.height(F.height());F.after(l).hide();ea(l,b.boxWidth,b.boxHeight);var s=l.width(),o=l.height(),D=g("<div />").width(s).height(o).addClass(b.baseClass+"-holder").css({position:"relative",backgroundColor:b.bgColor}).insertAfter(F).append(l);delete b.bgColor;b.addClass&&
D.addClass(b.addClass);var V=g("<img />").attr("src",l.attr("src")).css(ma).width(s).height(o),aa=g("<div />").width(A(100)).height(A(100)).css({zIndex:310,position:"absolute",overflow:"hidden"}).append(V),M=g("<div />").width(A(100)).height(A(100)).css("zIndex",320),N=g("<div />").css({position:"absolute",zIndex:300}).insertBefore(l).append(aa,M);$&&N.css({overflowY:"hidden"});var O=b.boundary,G=ha().width(s+2*O).height(o+2*O).css({position:"absolute",top:q(-O),left:q(-O),zIndex:290}).mousedown(fa),
U=b.bgOpacity,Q,R,S,T,u,z,L,ra;P=K(l);var H=function(){function a(){var a={},b=["touchstart","touchmove","touchend"],c=document.createElement("div"),d;try{for(d=0;d<b.length;d++){var f=b[d],f="on"+f,i=f in c;i||(c.setAttribute(f,"return;"),i="function"==typeof c[f]);a[b[d]]=i}return a.touchstart&&a.touchend&&a.touchmove}catch(e){return!1}}var e;e=!0===b.touchSupport||!1===b.touchSupport?b.touchSupport:a();return{createDragger:function(a){return function(j){j.pageX=j.originalEvent.changedTouches[0].pageX;
j.pageY=j.originalEvent.changedTouches[0].pageY;if(b.disabled||"move"===a&&!b.allowMove)return!1;L=!0;ba(a,B(j));j.stopPropagation();j.preventDefault();return!1}},newSelection:function(a){a.pageX=a.originalEvent.changedTouches[0].pageX;a.pageY=a.originalEvent.changedTouches[0].pageY;return fa(a)},isSupported:a,support:e}}(),t=function(){function a(){if(!b.aspectRatio){var a=f-c,e=i-d;Q&&Math.abs(a)>Q&&(f=0<a?c+Q:c-Q);R&&Math.abs(e)>R&&(i=0<e?d+R:d-R);T/z&&Math.abs(e)<T/z&&(i=0<e?d+T/z:d-T/z);S/u&&
Math.abs(a)<S/u&&(f=0<a?c+S/u:c-S/u);0>c&&(f-=c,c-=c);0>d&&(i-=d,d-=d);0>f&&(c-=f,f-=f);0>i&&(d-=i,i-=i);f>s&&(a=f-s,c-=a,f-=a);i>o&&(a=i-o,d-=a,i-=a);c>s&&(a=c-o,i-=a,d-=a);d>o&&(a=d-o,i-=a,d-=a);return j(r(c,d,f,i))}var a=b.aspectRatio,e=b.minSize[0]/u,g=b.maxSize[0]/u,l=f-c,m=i-d,n=Math.abs(l),k=Math.abs(m);0===g&&(g=10*s);n/k<a?(n=i,w=k*a,k=0>l?c-w:w+c,0>k?(k=0,h=Math.abs((k-c)/a),n=0>m?d-h:h+d):k>s&&(k=s,h=Math.abs((k-c)/a),n=0>m?d-h:h+d)):(k=f,h=n/a,n=0>m?d-h:d+h,0>n?(n=0,w=Math.abs((n-d)*a),
k=0>l?c-w:w+c):n>o&&(n=o,w=Math.abs(n-d)*a,k=0>l?c-w:w+c));k>c?(k-c<e?k=c+e:k-c>g&&(k=c+g),n=n>d?d+(k-c)/a:d-(k-c)/a):k<c&&(c-k<e?k=c-e:c-k>g&&(k=c-g),n=n>d?d+(c-k)/a:d-(c-k)/a);0>k?(c-=k,k=0):k>s&&(c-=k-s,k=s);0>n?(d-=n,n=0):n>o&&(d-=n-o,n=o);return j(r(c,d,k,n))}function e(a){0>a[0]&&(a[0]=0);0>a[1]&&(a[1]=0);a[0]>s&&(a[0]=s);a[1]>o&&(a[1]=o);return[a[0],a[1]]}function r(a,b,c,d){var i=a,f=c,e=b,na=d;c<a&&(i=c,f=a);d<b&&(e=d,na=b);return[Math.round(i),Math.round(e),Math.round(f),Math.round(na)]}
function j(a){return{x:a[0],y:a[1],x2:a[2],y2:a[3],w:a[2]-a[0],h:a[3]-a[1]}}var c=0,d=0,f=0,i=0,g,l;return{flipCoords:r,setPressed:function(a){a=e(a);f=c=a[0];i=d=a[1]},setCurrent:function(a){a=e(a);g=a[0]-f;l=a[1]-i;f=a[0];i=a[1]},getOffset:function(){return[g,l]},moveOffset:function(a){var b=a[0],a=a[1];0>c+b&&(b-=b+c);0>d+a&&(a-=a+d);o<i+a&&(a+=o-(i+a));s<f+b&&(b+=s-(f+b));c+=b;f+=b;d+=a;i+=a},getCorner:function(b){var c=a();switch(b){case "ne":return[c.x2,c.y];case "nw":return[c.x,c.y];case "se":return[c.x2,
c.y2];case "sw":return[c.x,c.y2]}},getFixed:a}}(),m=function(){function a(a){a=g("<div />").css({position:"absolute",opacity:b.borderOpacity}).addClass(b.baseClass+"-"+a);aa.append(a);return a}function e(a,b){var c=g("<div />").mousedown(da(a)).css({cursor:a+"-resize",position:"absolute",zIndex:b});H.support&&c.bind("touchstart",H.createDragger(a));M.append(c);return c}function r(a){var c=b.handleSize,d=c,i=n,f=n;switch(a){case "n":case "s":c=A(100);break;case "e":case "w":d=A(100)}return e(a,z++).width(c).height(d).css({top:q(-i+
1),left:q(-f+1)})}function j(a){var c;for(c=0;c<a.length;c++)v[a[c]]=e(a[c],z++).css({top:q(-n+1),left:q(-n+1),opacity:b.handleOpacity}).addClass(b.baseClass+"-handle")}function c(a){var b=Math.round(a.h/2-n),c=Math.round(a.w/2-n),d=a.w-n,a=a.h-n;v.e&&(v.e.css({top:q(b),left:q(d)}),v.w.css({top:q(b)}),v.s.css({top:q(a),left:q(c)}),v.n.css({left:q(c)}));v.ne&&(v.ne.css({left:q(d)}),v.se.css({top:q(a),left:q(d)}),v.sw.css({top:q(a)}));v.b&&(v.b.css({top:q(a)}),v.r.css({left:q(d)}))}function d(){var a=
t.getFixed();t.setPressed([a.x,a.y]);t.setCurrent([a.x2,a.y2]);f()}function f(){if(u)return i()}function i(){var a=t.getFixed(),d=a.h;N.width(a.w).height(d);var d=a.x,i=a.y;V.css({top:q(-i),left:q(-d)});N.css({top:q(i),left:q(d)});p&&c(a);u||(N.show(),b.bgFade?l.fadeTo(b.fadeTime,U):l.css("opacity",U),u=!0);b.onChange.call(I,Y(a))}function m(){p=!0;if(b.allowResize)return c(t.getFixed()),M.show(),!0}function o(){p=!1;M.hide()}function s(a){void 0===a?o():m()}var u,z=370,v={},p=!1,n=b.handleOffset;
b.drawBorders&&(a("hline"),a("hline bottom"),a("vline"),a("vline right"));b.dragEdges&&(v.t=r("n"),v.b=r("s"),v.r=r("e"),v.l=r("w"));b.sideHandles&&j(["n","s","e","w"]);b.cornerHandles&&j(["sw","nw","ne","se"]);var k=ha().mousedown(da("move")).css({cursor:"move",position:"absolute",zIndex:360});H.support&&k.bind("touchstart.jcrop",H.createDragger("move"));aa.append(k);o();return{updateVisible:f,update:i,release:function(){o();N.hide();b.bgFade?l.fadeTo(b.fadeTime,1):l.css("opacity",1);u=false;b.onRelease.call(I)},
refresh:d,isAwake:function(){return u},setCursor:function(a){k.css("cursor",a)},enableHandles:m,enableOnly:function(){p=true},showHandles:function(){if(p){c(t.getFixed());M.show()}},disableHandles:o,animMode:s,done:function(){s(false);d()}}}(),C=function(){function a(a){c(B(a));return!1}function e(i){i.preventDefault();i.stopPropagation();L&&(L=!1,d(B(i)),m.isAwake()&&b.onSelect.call(I,Y(t.getFixed())),G.css({zIndex:290}),f&&g(document).unbind("mousemove",a).unbind("mouseup",e),c=function(){},d=function(){});
return!1}function r(b){b.pageX=b.originalEvent.changedTouches[0].pageX;b.pageY=b.originalEvent.changedTouches[0].pageY;return a(b)}function j(a){a.pageX=a.originalEvent.changedTouches[0].pageX;a.pageY=a.originalEvent.changedTouches[0].pageY;return e(a)}var c=function(){},d=function(){},f=b.trackDocument;H.support&&g(document).bind("touchmove",r).bind("touchend",j);f||G.mousemove(a).mouseup(e).mouseout(e);l.before(G);return{activateHandlers:function(b,j){L=!0;c=b;d=j;G.css({zIndex:450});f&&g(document).bind("mousemove",
a).bind("mouseup",e);return!1},setCursor:function(a){G.css("cursor",a)}}}(),X=function(){function a(){j.hide()}function e(a,c,e){b.allowMove&&(t.moveOffset([c,e]),m.updateVisible());a.preventDefault();a.stopPropagation()}function r(a){if(a.ctrlKey)return!0;var b=(ra=a.shiftKey?!0:!1)?10:1;switch(a.keyCode){case 37:e(a,-b,0);break;case 39:e(a,b,0);break;case 38:e(a,0,-b);break;case 40:e(a,0,b);break;case 27:m.release();break;case 9:return!0}return!1}var j=g('<input type="radio" />').css({position:"fixed",
left:"-120px",width:"12px"}),c=g("<div />").css({position:"absolute",overflow:"hidden"}).append(j);b.keySupport&&(j.keydown(r).blur(a),$||!b.fixedSupport?(j.css({position:"absolute",left:"-20px"}),c.append(j).insertBefore(l)):j.insertBefore(l));return{watchKeys:function(){if(b.keySupport){j.show();j.focus()}}}}();H.support&&G.bind("touchstart",H.newSelection);M.hide();Z(!0);var I={setImage:function(a,e){m.release();ka();var g=new Image;g.onload=function(){var j=g.height,c=b.boxWidth,d=b.boxHeight;
l.width(g.width).height(j);l.attr("src",a);V.attr("src",a);ea(l,c,d);s=l.width();o=l.height();V.width(s).height(o);G.width(s+2*O).height(o+2*O);D.width(s).height(o);la();"function"===typeof e&&e.call(I)};g.src=a},animateTo:function(a,e){var g=parseInt(a[0],10)/u,j=parseInt(a[1],10)/z,c=parseInt(a[2],10)/u,d=parseInt(a[3],10)/z,g=t.flipCoords(g,j,c,d),j=t.getFixed(),f=[j.x,j.y,j.x2,j.y2],i=b.animationDelay,l=g[0]-f[0],o=g[1]-f[1],s=g[2]-f[2],q=g[3]-f[3],p=0,v=b.swingSpeed;x=f[0];y=f[1];c=f[2];d=f[3];
m.animMode(!0);var A=function(){return function(){p+=(100-p)/v;f[0]=x+p/100*l;f[1]=y+p/100*o;f[2]=c+p/100*s;f[3]=d+p/100*q;99.8<=p&&(p=100);100>p?(ja(f),window.setTimeout(A,i)):(m.done(),"function"===typeof e&&e.call(I))}}();window.setTimeout(A,i)},setSelect:ia,setOptions:function(a){E(a);Z()},tellSelect:function(){return Y(t.getFixed())},tellScaled:function(){return t.getFixed()},setClass:function(a){D.removeClass().addClass(b.baseClass+"-holder").addClass(a)},disable:ka,enable:la,cancel:function(){m.done();
C.activateHandlers(null,null)},release:m.release,destroy:function(){D.remove();F.show();g(p).removeData("Jcrop")},focus:X.watchKeys,getBounds:function(){return[s*u,o*z]},getWidgetSize:function(){return[s,o]},getScaleFactor:function(){return[u,z]},ui:{holder:D,selection:N}};g.browser.msie&&D.bind("selectstart",function(){return!1});F.data("Jcrop",I);return I};g.fn.Jcrop=function(p,J){function q(q){var K="object"===typeof p?p:{},B=K.useImg||q.src,E=new Image;E.onload=function(){function p(){if(!E.width||
!E.height)window.setTimeout(p,50);else{var B=g.Jcrop(q,K);"function"===typeof J&&J.call(B)}}window.setTimeout(p,50)};E.src=B}this.each(function(){if(g(this).data("Jcrop")){if("api"===p)return g(this).data("Jcrop");g(this).data("Jcrop").setOptions(p)}else q(this)});return this};g.Jcrop.defaults={allowSelect:!0,allowMove:!0,allowResize:!0,trackDocument:!0,baseClass:"jcrop",addClass:null,bgColor:"black",bgOpacity:0.6,bgFade:!1,borderOpacity:0.4,handleOpacity:0.5,handleSize:9,handleOffset:5,aspectRatio:0,
keySupport:!0,cornerHandles:!0,sideHandles:!0,drawBorders:!0,dragEdges:!0,fixedSupport:!0,touchSupport:null,boxWidth:0,boxHeight:0,boundary:2,fadeTime:400,animationDelay:20,swingSpeed:3,minSelect:[0,0],maxSize:[0,0],minSize:[0,0],onChange:function(){},onSelect:function(){},onRelease:function(){}}})(jQuery);

/* Fileman */
jQuery.fn.nodeIndex=function(){return jQuery(this).prevAll().length};
(function(a){var h=[];folder="";a.fn.pluploadQueue=function(v){function z(b){var m=h.length>maxthumbs?maxthumbs:h.length,c="";if(0==b){a(".f_list").html("");b='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>&nbsp;</td></tr></thead><tr><td colspan="2" class="tdmain">';for(var e=0;e<m;e++)c=n("&session=",h[e]),b+='<div class="item"><div class="img"><b></b><a href="javascript:void(0)" title="'+c+'"><img src="'+d.url+"thumb&filename="+folder+h[e]+'" alt=""/></a></div><span><input type="checkbox" class="checkbox" /><a href="javascript:void(0)" title="'+
c+'" class="filename">'+c+"</a></span></div>";a(".f_list").html(b+"</td></tr></table>");a(".f_pag input").val(1)}else if(1==b){if(parseInt(a(".f_pag b").html())>a(".f_pag input").val()){a(".f_list").html("");b='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>&nbsp;</td></tr></thead><tr><td colspan="2" class="tdmain">';c=a(".f_pag input").val()*maxthumbs;m=h.length-c>maxthumbs?maxthumbs+c:h.length;for(e=c;e<m;e++)c=n("&session=",h[e]),b+='<div class="item"><div class="img"><b></b><a href="javascript:void(0)" title="'+
c+'"><img src="'+d.url+"thumb&filename="+folder+h[e]+'" alt=""/></a></div><span><input type="checkbox" class="checkbox" /><a href="javascript:void(0)" title="'+c+'" class="filename">'+c+"</a></span></div>";b+="</td></tr></table>";a(".f_list").html(b);a(".f_pag input").val(parseInt(a(".f_pag input").val())+1)}}else if(-1==b&&1<parseInt(a(".f_pag b").html())&&1<a(".f_pag input").val()){a(".f_list").html("");b='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>&nbsp;</td></tr></thead><tr><td colspan="2" class="tdmain">';
c=(a(".f_pag input").val()-2)*maxthumbs;m=(a(".f_pag input").val()-1)*maxthumbs;for(e=c;e<m;e++)c=n("&session=",h[e]),b+='<div class="item"><div class="img"><b></b><a href="javascript:void(0)" title="'+c+'"><img src="'+d.url+"thumb&filename="+folder+h[e]+'" alt=""/></a></div><span><input type="checkbox" class="checkbox" /><a href="javascript:void(0)" title="'+c+'" class="filename">'+c+"</a></span></div>";b+="</td></tr></table>";a(".f_list").html(b);a(".f_pag input").val(parseInt(a(".f_pag input").val())-
1)}}function C(){a(".f_list").removeClass("f_viewdetail").removeClass("f_viewlist");a(".f_list").addClass("f_viewthumb");var b=0;h=[];a.each(f_tree.file,function(m){var c=n("&session=",f_tree.file[m]),c=c.substring(c.lastIndexOf(".")+1,c.length).toLowerCase();-1!=a.inArray(c,["jpg","jpeg","png","gif"])&&(h[b]=f_tree.file[m],b++)});a(".f_pag,.numbershow").css({display:"block"});if(0<h.length){var m=Math.round(h.length/maxthumbs)<h.length/maxthumbs?Math.round(h.length/maxthumbs)+1:Math.round(h.length/
maxthumbs);a(".f_pag b").html(m)}else a(".f_pag input").val(1),a(".f_pag b").html("1");z(0)}function D(){a(".f_pag,.numbershow").css({display:"none"});a(".f_list").removeClass("f_viewthumb").removeClass("f_viewlist");a(".f_list").addClass("f_viewdetail");var b='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>Filename</td><td>Size</td><td>Type</td><td>Modificationdate</td></tr></thead>';a.each(f_tree.file,function(a){var c=n("&session=",f_tree.file[a]),e=
c.substring(c.lastIndexOf(".")+1,c.length).toLowerCase();b+='<tr class="item"><td class="vcheckbox"><input type="checkbox" class="checkbox" /></td><td class="vfile"><a href="javascript:void(0)" title="'+c+'" class="filename">'+c+"</a></td><td>"+f_tree.size[a]+"</td><td>"+e+"</td><td>"+f_tree.date[a]+"</td></tr>"});b+="</table></div></table>";a(".f_list").html(b)}function E(){a(".f_pag,.numbershow").css({display:"none"});a(".f_list").removeClass("f_viewdetail").removeClass("f_viewthumb");a(".f_list").addClass("f_viewlist");
var b='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>&nbsp;</td></tr></thead><tr><td colspan="2" class="tdmain">';a.each(f_tree.file,function(a){b+='<div class="item"><input type="checkbox" class="checkbox" /><a href="javascript:void(0)" title="'+n("&session=",f_tree.file[a])+'" class="filename">'+n("&session=",f_tree.file[a])+"</a></div>"});b+="</td></tr></table>";a(".f_list").html(b)}function w(b){a(b).find("LI A").unbind();a(b).find("LI A").bind("click",
function(){a(this).hasClass("selected")?1>a(".txt_rename").length&&(a("#tree .selected").addClass("hide"),a("#tree .selected").before('<input type="text" class="txt_rename" />'),a(".txt_rename").val(a("#tree .selected").html()),a(".txt_rename").focus().select()):(a(".f_pag input").val(1),a(".f_pag b").html("1"),a("#tree").find(".selected").removeClass("selected"),a(this).addClass("selected"),folder=a(".selected").attr("rel"),a(this).parent().hasClass("directory")&&(a(this).parent().hasClass("collapsed")?
(a(this).parent().find("UL").remove(),u(a(this).parent(),escape(a(this).attr("rel").match(/.*\//)),"expand_list"),a(this).parent().removeClass("collapsed").addClass("expanded")):u(a(this).parent(),escape(a(this).attr("rel").match(/.*\//)),"list")),a("#preview .img img").remove(),a(".act_pre a.avai").removeClass("avai").removeAttr("href"));return!1});a(b).find("li i").bind("click",function(){var b=a(this);if(a(this).parent().hasClass("directory"))if(a(this).parent().hasClass("collapsed"))a(this).parent().find("UL").remove(),
u(a(this).parent(),escape(a(this).parent().children("a").attr("rel").match(/.*\//)),"expand"),a(this).parent().removeClass("collapsed").addClass("expanded");else{var c=a(b).next();0<a(".selected",c).length&&(a(".selected").removeClass("selected"),a(b).prev().addClass("selected"),folder=a("#tree .selected").attr("rel"),u(a(b).parent(),escape(a(b).parent().children("a").attr("rel").match(/.*\//)),"list"),a("#preview .img img").remove(),a(".act_pre a.avai").removeClass("avai").removeAttr("href"));a(this).parent().find("UL").slideUp("200");
a(this).parent().removeClass("expanded").addClass("collapsed")}});a(b).find("LI A").bind("click",function(){returnTop(0);return!1})}function y(){0<a(".plupload_content tbody tr").length?(a(".tab0").fadeOut(0),a(".tab2").fadeIn(0)):(a(".tab2").fadeOut(0),a(".tab0").fadeIn(0))}function F(b){f_tree.file.ex_file(b);a(".f_list .selected").remove();a("#preview .img").html("");a("#preview .avai").removeClass("avai");0==f_tree.file.length&&a(".tablefile .checkall").is(":checked")&&a(".tablefile .checkall").removeAttr("checked")}
function G(b){a("#w_newcrop").val(b.w);a("#h_newcrop").val(b.h);c[0]=b.x;c[1]=b.y;c[2]=b.x2;c[3]=b.y2}function q(){a("#edit_undo,#edit_save").addClass("avai")}function s(){a("#edit_redo").removeClass("avai")}function H(){if("NaN"!=a("#newfilename").val()&&""!=a("#newfilename").val())if(save_file_step=save_file+"&newfilename="+a("#newfilename").val()+a(".ext_type").html(),a("#newfilename").val()==a(".edit_name").html())"0"!=confirm("Replace this file?")&&a.post(save_file_step+"&overwrite",function(b){b=
a.parseJSON(b);if(b.result){a("#preview .img img").remove();a(".act_pre a.avai").removeClass("avai").removeAttr("href");a(".f_list .previewing").removeClass("previewing");replace_file(f_tree.file,b.result,p("&session=",b.result));switch(d.vtype){case 0:E();break;case 2:D();break;default:C()}a("#edit_exit").click()}else a("#newfilename").remove(),a(".edit_name").show()});else if(0<=a.inArray(a("#newfilename").val()+a(".ext_type").html(),f_tree.file)){var b=a("#newfilename").val()+a(".ext_type").html();
"0"!=confirm("This folder already contains a file named '"+b+"' \n\n Would you like to replace the existing file ?")&&a.post(save_file_step+"&overwrite",function(b){b=a.parseJSON(b);if(b.result){a("#preview .img img").remove();a(".act_pre a.avai").removeClass("avai").removeAttr("href");f_tree.file.splice(0,0,b.result);switch(d.vtype){case 0:a(".f_list .tdmain").append('<div class="item"><input type="checkbox" class="checkbox"><a class="filename" title="'+b.result+'" href="javascript:void(0)">'+b.result+
"</a></div>");break;case 2:var c=b.result.substring(b.result.lastIndexOf(".")+1,b.result.length).toLowerCase();a.post(d.url+"stat&folder="+folder+"&filename="+b.result,function(e){e=a.parseJSON(e);a(".f_list .tablefile tbody").append('<tr class="item"><td class="vcheckbox"><input type="checkbox" class="checkbox"></td><td class="vfile"><a class="filename" title="'+b.result+'" href="javascript:void(0)">'+b.result+"</a></td><td>"+e.size+"</td><td>"+c+"</td><td>"+e.date+"</td></tr>")});break;default:a(".f_list .tdmain").append('<div class="item"><div class="img"><b></b><a title="'+
b.result+'" href="javascript:void(0)"><img alt="" src="'+d.url+"thumb&filename="+folder+b.result+'"></a></div><span><input type="checkbox" class="checkbox"><a class="filename" title="'+b.result+'" href="javascript:void(0)">'+b.result+"</a></span></div>")}a("#edit_exit").click()}else a("#newfilename").remove(),a(".edit_name").show()})}else a.post(save_file_step+"&overwrite",function(b){b=a.parseJSON(b);if(b.result){a("#preview .img img").remove();a(".act_pre a.avai").removeClass("avai").removeAttr("href");
f_tree.file.splice(0,0,b.result);switch(d.vtype){case 0:a(".f_list .tdmain").append('<div class="item"><input type="checkbox" class="checkbox"><a class="filename" title="'+b.result+'" href="javascript:void(0)">'+b.result+"</a></div>");break;case 2:var c=b.result.substring(b.result.lastIndexOf(".")+1,b.result.length).toLowerCase();a.post(d.url+"stat&folder="+folder+"&filename="+b.result,function(e){e=a.parseJSON(e);a(".f_list .tablefile tbody").append('<tr class="item"><td class="vcheckbox"><input type="checkbox" class="checkbox"></td><td class="vfile"><a class="filename" title="'+
b.result+'" href="javascript:void(0)">'+b.result+"</a></td><td>"+e.size+"</td><td>"+c+"</td><td>"+e.date+"</td></tr>")});break;default:a(".f_list .tdmain").append('<div class="item"><div class="img"><b></b><a title="'+b.result+'" href="javascript:void(0)"><img alt="" src="'+d.url+"thumb&filename="+folder+b.result+'"></a></div><span><input type="checkbox" class="checkbox"><a class="filename" title="'+b.result+'" href="javascript:void(0)">'+b.result+"</a></span></div>")}a("#edit_exit").click()}else a("#newfilename,#save_ok").remove(),
a(".edit_name").show()});else a("#newfilename,#save_ok").remove(),a(".edit_name").show()}function p(a,c){var g=0,g=""+(new Date).getTime(),g=a+g.substring(8,13,g.length);return c+g}function n(a,c){return-1<c.indexOf(a)?c.split(a)[0]:c}f_tree=[];var A=a(this),x=A.attr("id");x||(x=plupload.guid(),A.attr("id",x));var d=a.extend(!0,{},{vtype:0,maxthumbs:25,option:{runtimes:"html5,flash,html4",max_file_size:"2mb",chunk_size:"1mb",unique_names:!1,dragdrop:!0,container:x}},v);d.option.url=d.url+"upload";
d.option.flash_swf_url=d.path+"flash.swf";d.option.silverlight_xap_url=d.path+"silverlight.xap";maxthumbs=parseInt(d.maxthumbs);a(A).append('<div id="vf_top" class="vf_top_file"><div id="cmd"><a href="javascript:void(0)" class="upload tab0 tab2" id="uploader-picker"><span></span>Upload</a><a href="javascript:void(0)" class="create_folder tab0"><span></span>Create folder</a><a href="javascript:void(0)" class="delete tab0"><span></span>Delete</a><a href="javascript:void(0)" class="back"><span></span>Back</a><a href="javascript:void(0)" class="insert tab0"><span></span>Insert</a><a href="javascript:void(0)" class="save_img tab_edit"><span></span>Save</a></div><div class="f_filter tab0"><div class="f_filters"><a href="javascript:void(0)" class="f_btn_detail" title="Details"></a><a href="javascript:void(0)" class="f_btn_list" title="List"></a><a href="javascript:void(0)" class="f_btn_thumb" title="Thumbnails"></a></div><select class="numbershow"><option>25</option><option>50</option><option>75</option></select><div class="f_pag"><a class="f_prev"></a><input type="text" value="1" readonly="readonly" /><span>/</span><b>1</b><a class="f_next"></a></div></div></div><div id="file_man" class="tab0"><div class="f_folders"><div class="f_folders_scroll"><input type="text" id="txt_name" /><div id="tree"></div><div id="preview"><div class="act_pre"><a class="view">View</a> <a class="edit">Edit</a> <a class="insert">Insert</a> <a class="download" target="_blank">Download</a></div><div class="img"></div></div></div></div><div class="f_explorer"><div class="f_main"><div class="f_list"></div></div></div></div>');
a("#uploader").append('<table class="plupload_content tableupload tab2"><thead><tr><td></td><td>Filename</td><td>Size</td></tr></thead><tbody></tbody></table>');v=""+window.location;-1==v.indexOf("opener=editor")&&-1==v.indexOf("opener=plugin")&&a("#cmd .insert,.act_pre .insert").addClass("e_hide");-1!=v.indexOf("opener=plugin")&&a("#cmd .insert").addClass("e_hide");var B=function(){if(f_tree.file)switch(a(".f_list").html(""),d.vtype){case 0:E();break;case 2:D();break;default:C()}},u=function(b,c,
g){if(void 0==b||""==b)b="#tree",a(b).addClass("root").html('<ul class="fileTree start"><li class="wait"><li></ul>');void 0==c&&(c="");a(b).addClass("wait");a(".fileTree.start").remove();var e="";2==d.vtype&&(e="&a=detail");a.post(d.url+g+e,{folder:c},function(e){f_tree=a.parseJSON(e);a(b).removeClass("wait");void 0!=f_tree.folder&&(a(b).find(".start").html(""),a(b).append(f_tree.folder),""==c?a(b).find("UL:hidden").show():a(b).find("UL:hidden").slideDown({duration:200,easing:null}),w(b));void 0!=
f_tree.file&&(B(f_tree),scroll_fileman())})};u(void 0,void 0,"expand_list");a(".f_btn_thumb").live("click",function(){d.vtype=1;B();scroll_fileman()});a(".f_btn_list").live("click",function(){d.vtype=0;B();scroll_fileman()});a(".f_btn_detail").live("click",function(){d.vtype=2;var b="#tree",c="";0<a(".selected").length&&(b=a(".selected").parent(),c=escape(a(".selected").attr("rel").match(/.*\//)));u(b,c,"list")});a(".f_pag .f_next").live("click",function(){z(1)});a(".f_pag .f_prev").live("click",
function(){z(-1)});a(".numbershow").live("change",function(){maxthumbs=parseInt(a(this).val());var b=h.length>maxthumbs?maxthumbs:h.length;a(".f_list").html("");for(var c="",g='<table class="tablefile"><thead><tr><td><input type="checkbox" class="checkall" /></td><td>&nbsp;</td></tr></thead><tr><td colspan="2" class="tdmain">',e=0;e<b;e++)c=n("&session=",h[e]),g+='<div class="item"><div class="img"><b></b><a href="javascript:void(0)" title="'+c+'"><img src="'+d.url+"thumb&filename="+folder+h[e]+'" alt="" class="filename"/></a></div><span><input type="checkbox" class="checkbox" /><a href="javascript:void(0)" title="'+
c+'" class="filename">'+c+"</a></span></div>";a(".f_list").html(g+"</td></tr></table>");a(".f_pag input").val(1);b=Math.round(h.length/maxthumbs)<h.length/maxthumbs?Math.round(h.length/maxthumbs)+1:Math.round(h.length/maxthumbs);a(".f_pag b").html(b)});var t=new plupload.Uploader(a.extend({url:d.url+"upload",browse_button:"uploader-picker",drop_element:x},d.option));t.init();a(".plupload").addClass("tab0");t.bind("BeforeUpload",function(a){a.settings.url=d.url+"upload&folder="+folder});t.bind("FilesAdded",
function(b,c){returnTop(0);a.each(c,function(b,c){a(".plupload_content tbody").append('<tr id="'+c.id+'"><td><span><a href="#" class="uploader-remove"></a></span></td><td>'+c.name+"</td><td>"+plupload.formatSize(c.size)+"</td></tr>");c.status==plupload.FAILED&&(a("#"+c.id+" span").prepend('<a class="uploader-fail"></a> '),setTimeout(function(){a(".plupload_content #"+c.id).slideUp(500).remove();y()},5E3));a("#"+c.id).find("a").bind("click",function(){a("#"+c.id).remove();t.removeFile(c)})});y();t.start()});
t.bind("UploadProgress",function(b,c){a("#"+c.id+" span").html(c.percent+"%")});t.bind("FileUploaded",function(b,c,g){a("#"+c.id+" span").html('<a class="uploader-done"></a>');r=jQuery.parseJSON(g.response);if(r.error)a("#"+c.id+" span").html('<a class="uploader-fail"></a> '+r.error.message),setTimeout(function(){a(".plupload_content #"+c.id).slideUp(500).remove();y()},3E3);else{var e=f=r.result||c.name;f_tree.file.splice(0,0,e);switch(d.vtype){case 0:a(".f_list .tdmain").prepend('<div class="item"><input type="checkbox" class="checkbox"><a class="filename" title="'+
e+'" href="javascript:void(0)">'+e+"</a></div>");break;case 2:var h=e.substring(e.lastIndexOf(".")+1,e.length).toLowerCase();a.post(d.url+"stat&folder="+folder+"&filename="+e,function(b){b=a.parseJSON(b);a(".f_list .tablefile tbody").prepend('<tr class="item"><td class="vcheckbox"><input type="checkbox" class="checkbox"></td><td class="vfile"><a class="filename" title="'+e+'" href="javascript:void(0)">'+e+"</a></td><td>"+b.size+"</td><td>"+h+"</td><td>"+b.date+"</td></tr>")});break;default:a(".f_list .tdmain").prepend('<div class="item"><div class="img"><b></b><a title="'+
e+'" href="javascript:void(0)"><img alt="" src="'+d.url+"thumb&filename="+folder+e+'"></a></div><span><input type="checkbox" class="checkbox"><a class="filename" title="'+e+'" href="javascript:void(0)">'+e+"</a></span></div>")}setTimeout(function(){a(".plupload_content #"+c.id).slideUp(500).remove();y()},1E3)}});a(".f_viewdetail tbody td").live("click",function(b){"TD"==b.target.nodeName&&(b=a(this).parent().children("td:first-child"),a("input",b).is(":checked")?(a("input",b).removeAttr("checked"),
a(this).parent().removeClass("selected"),a(".tablefile .checkall").is(":checked")&&a(".tablefile .checkall").removeAttr("checked")):(a("input",b).attr("checked","checked"),a(this).parent().addClass("selected")))});a(".f_list .checkbox").live("click",function(){a(this).is(":checked")?a(this).parents(".item").addClass("selected"):(a(this).parents(".item").removeClass("selected"),a(".tablefile .checkall").is(":checked")&&a(".tablefile .checkall").removeAttr("checked"))});a(".checkall").live("click",
function(){a(this).is(":checked")?(a(".f_list input.checkbox").attr("checked","checked"),a(".f_list input.checkbox").parents(".item").addClass("selected")):(a(".f_list input.checkbox").removeAttr("checked"),a(".f_list input.checkbox").parents(".item").removeClass("selected"))});a(".f_list a").live("click",function(){a(".f_list .item").removeClass("previewing");var b=a(this).attr("title");a(".download").attr({href:d.upload+folder+b});var c=b.substring(b.lastIndexOf(".")+1,b.length).toLowerCase();-1!=
a.inArray(c,["jpg","jpeg","png","gif"])?(a("#preview .img").html('<img src="'+p("?session=",d.upload+folder+b)+'" alt="'+p("?session=",d.upload+folder+b)+'" title="'+b+'" />'),a(".act_pre .view,.act_pre .edit").addClass("avai")):-1!=a.inArray(c,["swf"])?(a("#preview .img").attr({id:"screen_flash",title:a(this).attr("title")}),a.post(d.url+"size",{folder:folder,filename:a(this).attr("title"),width:140,height:140},function(c){c=a.parseJSON(c);c=c.result?new SWFObject(d.upload+folder+b,"mymovie",c.result[0],
c.result[1],"8","#fff"):new SWFObject(d.upload+folder+b,"mymovie","140","140","8","#fff");c.addParam("wmode","transparent");c.write("screen_flash");a(".act_pre .view").addClass("avai");a(".act_pre .edit.avai").removeClass("avai")})):-1!=a.inArray(c,["flv"])?(a("#preview .img").html('<span class="movie" title="'+b+'"></span>'),a(".act_pre .view").addClass("avai"),a(".act_pre .edit.avai").removeClass("avai")):(a("#preview .img").html('<span class="unknown" title="'+b+'"></span>'),a(".act_pre .view.avai,.act_pre .edit.avai").removeClass("avai"));
a(".act_pre .download,.act_pre .insert").addClass("avai")});a(".act_pre .view.avai").live("click",function(){if(0<a("#preview .img img").length){1>a("#preview_img").length?a("#vf_top").after('<div id="preview_img" class="tab1"><div class="info_file"></div><div id="big_frame"></div></div>'):a(".tab1").css({display:"block"});a("#cmd .back").css({display:"inline-block"});returnTop(0);a(".tab0").css({display:"none"});var b=a("#preview .img img").attr("src"),b=b.substring(b.lastIndexOf("/")+1,b.length).toLowerCase(),
c=a("#preview .img img").attr("src");a("#preview_img #big_frame").html('<img id="big_img" src="'+c+'" alt="" />');a("#preview_img .info_file").html(n("?session",b)+"<p>("+a("#big_img").width()+" x "+a("#big_img").height()+")</p>")}else if(0<a("#preview .img embed").length){1>a("#preview_img").length?a("#vf_top").after('<div id="preview_img" class="tab1"><div class="info_file"></div><div id="big_frame"></div></div>'):a(".tab1").css({display:"block"});a("#cmd .back").css({display:"inline-block"});returnTop(0);
a(".tab0").css({display:"none"});b=a("#preview .img embed").attr("src");b=b.substring(b.lastIndexOf("/")+1,b.length).toLowerCase();a("#preview_img .info_file").html(b);var g=a("#preview .img embed").attr("src");a.post(d.url+"size",{folder:folder,filename:b},function(b){b=a.parseJSON(b);if(b.result){var c=new SWFObject(g,"bidembed",b.result[0],b.result[1],"8","#fff");a("#preview_img .info_file").append("<p>("+b.result[0]+" x "+b.result[1]+")</p>")}else c=new SWFObject(g,"bidembed","500","500","8",
"#fff");c.addParam("wmode","transparent");c.write("big_frame")})}else 0<a(".movie").length&&(1>a("#preview_img").length?a("#vf_top").after('<div id="preview_img" class="tab1"><div class="info_file"></div><div id="big_frame"></div></div>'):a(".tab1").css({display:"block"}),a("#cmd .back").css({display:"inline-block"}),returnTop(0),a(".tab0").css({display:"none"}),a(".info_file").html(a(".movie").attr("title")),a("#big_frame").html("").html('<a href="'+d.upload+folder+a(".movie").attr("title")+'" id="player"></a>'),
flowplayer("player",d.path+"/player/flowplayer-3.2.7.swf"))});a("#cmd .back").live("click",function(){a(".tableFloatingHeader").css({visibility:"hidden"});a(this).css({display:"none"});a(".tab0").css({display:"block"});a("#cmd .tab0").css({display:"inline-block"});0<a("#preview_img").length&&(a("#big_frame").html(""),a(".tab1").css({display:"none"}));a("#uploader").is(":visible")&&a(".tab2").not(".upload").css({display:"none"});a("#cmd .tab_edit").is(":visible")&&a("#cmd .tab_edit").css({display:"none"})});
a("#cmd .create_folder").live("click",function(){""!=folder?(a("#tree .selected").parent().children(".fileTree").append('<li class="directory collapsed"><input type="text" class="txt" /><i></i></li>'),a("#tree .selected").parent().children(".fileTree").not(":visible")&&a("#tree .selected").next().next().slideDown(200)):a("#tree > .fileTree").append('<li class="directory collapsed"><input type="text" class="txt" /><i></i></li>');a("#tree .txt").focus()});a("#tree .txt").live("keypress",function(b){13==
b.which&&""!=a(this).val()?a.post(d.url+"mkdir",{folder:folder,newfolder:a("#tree .txt").val()},function(b){b=a.parseJSON(b);b.result?(a("#tree .txt").before('<a rel="'+folder+b.result+'/" href="javascript:void(0)">'+b.result+"</a>"),w(a("#tree .txt").parents("li").parents("li")),a("#tree .txt").remove()):a("#tree .txt").parent().remove()}):13==b.which&&""==a(this).val()&&a("#tree .txt").parent().remove()});a("#tree .txt").live("focusout",function(){""!=a(this).val()?a.post(d.url+"mkdir",{folder:folder,
newfolder:a("#tree .txt").val()},function(b){b=a.parseJSON(b);b.result?(a("#tree .txt").before('<a rel="'+folder+b.result+'/" href="javascript:void(0)">'+b.result+"</a>"),w(a("#tree .txt").parents("li").parents("li")),a("#tree .txt").remove()):a("#tree .txt").parent().remove()}):a("#tree .txt").parent().remove()});a(document).keyup(function(b){if(46==b.keyCode&&1>a("#tree .txt").length&&1>a(".txt_rename").length&&a(".f_list").is(":visible"))if(0<a(".f_list .selected").length){var c=[];a(".f_list .selected").each(function(b){c[b]=
a("a",this).attr("title")});"0"!=confirm("Delete files ?")&&a.post(d.url+"del",{folder:folder,filename:c},function(b){b=a.parseJSON(b);b.error?alert("Error"):F(c)})}else 0<a(".f_list .item").length?alert("No files selected!"):0<a("#tree .selected").next().next().children().length?alert("Can not delete non-empty folder!"):1>a("#tree .selected").next().next().children().length&&1>a(".f_list .item").length&&"0"!=confirm('Delete "'+a("#tree .selected").html()+'" folder ?')&&a.post(d.url+"rmdir",{folder:folder},
function(b){b=a.parseJSON(b);b.result&&a("#tree .selected").parent().remove()})});a("#cmd .delete").live("click",function(){if(0<a(".f_list .selected").length){var b=[];a(".f_list .selected").each(function(c){b[c]=a("a",this).attr("title")});"0"!=confirm("Delete files ?")&&a.post(d.url+"del",{folder:folder,filename:b},function(c){c=a.parseJSON(c);c.error?alert("Error"):F(b)})}else 0<a(".f_list .item").length?alert("No files selected!"):0<a("#tree .selected").next().next().children().length?alert("Can not delete non-empty folder!"):
1>a("#tree .selected").next().next().children().length&&1>a(".f_list .item").length&&"0"!=confirm('Delete "'+a("#tree .selected").html()+'" folder ?')&&a.post(d.url+"rmdir",{folder:folder},function(b){b=a.parseJSON(b);b.result&&a("#tree .selected").parent().remove()})});a("#tree .txt_rename").live("keypress",function(b){if(13==b.which&&""!=a(this).val()){var c=a(this).parents("li").parents("li").children("a").attr("rel");a.post(d.url+"rendir",{folder:folder,newfolder:a("#tree .txt_rename").val()},
function(b){b=a.parseJSON(b);if(b.result){var e=a("#tree .txt_rename").parent().children("ul");a("a",e).each(function(){a(this).attr({rel:a(this).attr("rel").replace(folder,c+b.result+"/")})});folder=c+b.result+"/";a("#tree .selected").attr({rel:folder}).html(b.result);w(a("#tree .txt_rename").parents("li"))}a("#tree .txt_rename").remove();a("#tree .selected").removeClass("hide")})}else 13==b.which&&""==a(this).val()&&(a("#tree .txt_rename").remove(),a("#tree .selected").removeClass("hide"))});a("#tree .txt_rename").live("focusout",
function(){if(""!=a(this).val()){var b=a(this).parents("li").parents("li").children("a").attr("rel");a.post(d.url+"rendir",{folder:folder,newfolder:a("#tree .txt_rename").val()},function(c){c=a.parseJSON(c);c.result&&(folder=b+c.result+"/",a("#tree .selected").attr({rel:folder}).html(c.result),w(a("#tree .txt_rename").parents("li")));a("#tree .txt_rename").remove();a("#tree .selected").removeClass("hide")})}else a("#tree .txt_rename").remove(),a("#tree .selected").removeClass("hide")});a(".filename:not(.avai_rename)").live("click",
function(){a(".filename").removeClass("avai_rename");a(this).addClass("avai_rename")});a(".avai_rename").live("click",function(){a(this).addClass("hide_filename").before('<input type="text" class="re_filename" />');a(".re_filename").val(a(this).html().substring(0,a(this).html().lastIndexOf("."))).focus().select()});a(".re_filename").live("keypress",function(b){13==b.which&&""!=a(this).val()?a.post(d.url+"renfile",{folder:folder,filename:a(".avai_rename").html(),newfilename:a(".re_filename").val()},
function(b){b=a.parseJSON(b);if(b.result){var c=f_tree.file.indexOf(a(".avai_rename").html());f_tree.file[c]=b.result;a(".avai_rename").html(b.result).attr({title:b.result})}a(".re_filename").remove();a(".avai_rename").removeClass("hide_filename")}):13==b.which&&""==a(this).val()&&(a(".re_filename").remove(),a(".avai_rename").removeClass("hide_filename"))});a(".re_filename").live("focusout",function(){""!=a(this).val()?a.post(d.url+"renfile",{folder:folder,filename:a(".avai_rename").html(),newfilename:a(".re_filename").val()},
function(b){b=a.parseJSON(b);if(b.result){var c=f_tree.file.indexOf(a(".avai_rename").html());f_tree.file[c]=b.result;a(".avai_rename").html(b.result)}a(".re_filename").remove();a(".avai_rename").removeClass("hide_filename")}):(a(".re_filename").remove(),a(".avai_rename").removeClass("hide_filename"))});a(".act_pre .edit.avai").live("click",function(){if(0<a("#preview .img img").length){var b=a("#preview .img img").attr("title"),c=folder,d=b.substring(b.lastIndexOf("/")+1,b.lastIndexOf(".")),b=b.substring(b.lastIndexOf("."),
b.length),c='<div id="preview_img" class="tab1"><div id="edit_img"><div id="edit_head"><div id="edit_general"><ul id="edit_menu"><li><a href="javascript:void(0)" id="edit_exit" title="Exit">Exit</a></li><li><a id="edit_undo" title="Undo">Undo</a></li><li><a id="edit_redo" title="Redo">Redo</a></li><li><a id="edit_save" title="Save">Save</a></li></ul><p id="link_editfile"><strong>File:</strong> <span class="path">'+c+'</span><span class="edit_name">'+d+'</span><span class="ext_type">'+b+'</span></p></div><div id="crop_panel"><strong class="tit_panel">Crop</strong><div class="prop"><label>Width</label> <input type="text" class="newsize" id="w_newcrop" maxlength="4" /><label>Height</label> <input type="text" class="newsize" id="h_newcrop" maxlength="4" /><label for="crop_ratio">Ratio</label><input type="checkbox" class="check" id="crop_ratio" /></div><ul class="act"><li><a id="crop_done" class="done" title="Apply"></a></li><li><a id="crop_cancel" class="cancel" title="Cancel"></a></li></ul></div><div id="res_panel"><strong class="tit_panel">Resize</strong><div class="prop"><label>Width</label> <input type="text" class="newsize" id="w_newsize" maxlength="4" /><label>Height</label> <input type="text" class="newsize" id="h_newsize" maxlength="4" /></div><ul class="act"><li><a id="res_done" class="done" title="Apply"></a></li><li><a id="res_cancel" class="cancel" title="Cancel"></a></li></ul></div></div><div class="tools"><ul id="tool_btn" class="tool_active"><li><a href="javascript:void(0)" id="action_crop"></a></li><li><a href="javascript:void(0)" id="action_resize"></a></li><li><a href="javascript:void(0)" id="fliph"></a></li><li><a href="javascript:void(0)" id="flipv"></a></li><li><a href="javascript:void(0)" id="rotate_right"></a></li><li><a href="javascript:void(0)" id="rotate_left"></a></li></ul></div><div class="holder"><img src="'+
a("#preview .img img").attr("src")+'" id="target" alt="" /></div></div></div>';a("#vf_top").after(c);w_target=a("#target").width();h_target=a("#target").height();a("#vf_top,.tab0").css({display:"none"});returnTop(0)}});var l,c=[],k=[];a(".tool_active #action_crop").live("click",function(){var b=[w_target/6,h_target/6,w_target/1.2,h_target/1.2];a(".tools .check").attr("checked",!1);a("#target").Jcrop({onChange:G,onSelect:G,aspectRatio:0,setSelect:b},function(){l=this;l.enable()});a("#tool_btn").removeClass("tool_active");
return!1});rs_h=rs_w=0;a(".tool_active #action_resize").live("click",function(){rs_w=w_target;rs_h=h_target;var b=rs_w,c=rs_h;a("#w_newsize").val(b);a("#h_newsize").val(c);rs_w=b;rs_h=c;l&&l.destroy();a(".tools .check").attr("checked",!1);a("#tool_btn").removeClass("tool_active");return!1});a("#w_newcrop").live("keyup",function(b){if(13==b.keyCode){b=c[2]-c[0];var d=parseInt(a(this).val());"NaN"!=a(this).val()&&0<a(this).val()?(a("#crop_ratio").attr("checked")?(c[2]=d+c[0],c[2]>w_target&&c[2]<h_target?
(c[2]=w_target,c[3]=c[2]):c[2]<w_target&&c[2]>h_target?(c[2]=h_target,c[3]=c[2]):c[3]=d+c[1]):(c[2]=d+c[0],c[2]>w_target&&(c[2]=w_target)),l.animateTo(c)):a(this).val(b)}});a("#w_newcrop").live("focusout",function(){var b=c[2]-c[0],d=parseInt(a(this).val());"NaN"!=a(this).val()&&0<a(this).val()?(a("#crop_ratio").attr("checked")?(c[2]=d+c[0],c[2]>w_target&&c[2]<h_target?(c[2]=w_target,c[3]=c[2]):c[2]<w_target&&c[2]>h_target?(c[2]=h_target,c[3]=c[2]):c[3]=d+c[1]):(c[2]=d+c[0],c[2]>w_target&&(c[2]=w_target)),
l.animateTo(c)):a(this).val(b)});a("#h_newcrop").live("keyup",function(b){if(13==b.keyCode){b=c[3]-c[1];var d=parseInt(a(this).val());"NaN"!=a(this).val()&&0<a(this).val()?(a("#crop_ratio").attr("checked")?(c[3]=d+c[1],c[3]>h_target&&c[3]<w_target?(c[3]=h_target,c[2]=c[3]):c[3]<h_target&&c[3]>w_target?(c[3]=w_target,c[2]=c[3]):c[2]=d+c[0]):(c[3]=d+c[1],c[3]>h_target&&(c[3]=h_target)),l.animateTo(c)):a(this).val(b)}});a("#h_newcrop").live("focusout",function(){var b=c[3]-c[1],d=parseInt(a(this).val());
"NaN"!=a(this).val()&&0<a(this).val()?(a("#crop_ratio").attr("checked")?(c[3]=d+c[1],c[3]>h_target&&c[3]<w_target?(c[3]=h_target,c[2]=c[3]):c[3]<h_target&&c[3]>w_target?(c[3]=w_target,c[2]=c[3]):c[2]=d+c[0]):(c[3]=d+c[1],c[3]>h_target&&(c[3]=h_target)),l.animateTo(c)):a(this).val(b)});a("#w_newcrop").live("focusout",function(){a(this).val(c[2]-c[0])});a("#h_newcrop").live("focusout",function(){a(this).val(c[3]-c[1])});a("#crop_ratio").live("change",function(){l.setOptions(this.checked?{aspectRatio:a("#w_newcrop").val()/
a("#h_newcrop").val()}:{aspectRatio:0});l.focus()});a("#w_newsize").live("keyup",function(b){13==b.keyCode&&(b=parseInt(a(this).val()),"NaN"!=a(this).val()&&0<a(this).val()?(rs_h=Math.round(b*(rs_h/rs_w)),rs_w=b,a("#h_newsize").val(rs_h)):a(this).val(rs_w),a("#target").css({width:rs_w,height:rs_h}))});a("#w_newsize").live("focusout",function(){var b=parseInt(a(this).val());"NaN"!=a(this).val()&&0<a(this).val()?(rs_h=Math.round(b*(rs_h/rs_w)),rs_w=b,a("#h_newsize").val(rs_h)):a(this).val(rs_w);a("#target").css({width:rs_w,
height:rs_h})});a("#h_newsize").live("keyup",function(b){13==b.keyCode&&(b=parseInt(a(this).val()),"NaN"!=a(this).val()&&0<a(this).val()?(rs_w=Math.round(b*(rs_w/rs_h)),rs_h=b,a("#w_newsize").val(rs_w)):a(this).val(rs_h),a("#target").css({width:rs_w,height:rs_h}))});a("#h_newsize").live("focusout",function(){var b=parseInt(a(this).val());"NaN"!=a(this).val()&&0<a(this).val()?(rs_w=Math.round(b*(rs_w/rs_h)),rs_h=b,a("#w_newsize").val(rs_w)):a(this).val(rs_h);a("#target").css({width:rs_w,height:rs_h})});
var j=[],k=[];a("#crop_done").live("click",function(){j.push("crop,"+c[0]+","+c[1]+","+c[2]+","+c[3]+";");w_target=c[2]-c[0];h_target=c[3]-c[1];a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join(""))+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a("#res_done").live("click",function(){w_target=rs_w;h_target=rs_h;j.push("resize,"+w_target+","+h_target+
";");a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join(""))+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a(".tool_active #action_crop").live("click",function(){a("#edit_general").css({display:"none"});a("#crop_panel").css({display:"block"})});a(".tool_active #action_resize").live("click",function(){a("#edit_general").css({display:"none"});a("#res_panel").css({display:"block"})});
a("#crop_cancel,#crop_done").live("click",function(){a("#edit_general").css({display:"block"});a("#crop_panel").css({display:"none"});l.destroy();a(".tools .check").attr("checked",!1);a("#target").removeAttr("style");a("#tool_btn").addClass("tool_active")});a("#res_cancel,#res_done").live("click",function(){a("#edit_general").css({display:"block"});a("#res_panel").css({display:"none"});a("#target").removeAttr("style");a("#tool_btn").addClass("tool_active")});a(".tool_active #fliph").live("click",
function(){j.push("fliph;");a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join(""))+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a(".tool_active #flipv").live("click",function(){j.push("flipv;");a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+
"&action="+j.join(""))+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a(".tool_active #rotate_right").live("click",function(){var b=w_target;w_target=h_target;h_target=b;j.push("ccw;");a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join(""))+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a(".tool_active #rotate_left").live("click",
function(){var b=w_target;w_target=h_target;h_target=b;j.push("cw;");a("#target").remove();a(".holder").append('<img src="'+d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join("")+'" id="target" alt=""/>');0<k.length&&(k.length=0,s());1==j.length&&q()});a("#edit_undo.avai").live("click",function(){var b=j.pop();k.push(b);a("#target").remove();a(".holder").append('<img src="'+p("&session=",d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+
a(".ext_type").html()+"&action="+j.join(""))+'" id="target" alt=""/>');w_target=a("#target").width();h_target=a("#target").height();0==j.length&&a("#edit_undo,#edit_save").removeClass("avai");a("#edit_redo").addClass("avai")});a("#edit_redo.avai").live("click",function(){var b=k.pop();j.push(b);a("#target").remove();a(".holder").append('<img src="'+d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join("")+'" id="target" alt=""/>');0==k.length&&s();
q()});a("#edit_save.avai").live("click",function(){save_file=d.url+"edit&folder="+folder+"&filename="+a(".edit_name").html()+a(".ext_type").html()+"&action="+j.join("");1>a("#newfilename").length&&(a(".edit_name").before('<input type="text" id="newfilename" />').hide(),a(".ext_type").after('<a id="save_ok"></a>'),a("#newfilename").css({width:a(".edit_name").width()}).val(a(".edit_name").html()).focus().select())});a("#save_ok").live("click",function(){H()});a("#newfilename").live("keyup",function(a){13==
a.keyCode&&H()});a("html").click(function(b){-1==a(b.target).parents().index(a("#link_editfile"))&&(a("#newfilename,#save_ok").remove(),a(".edit_name").show())});a("#edit_exit").live("click",function(){j.length=0;a(".tab0").css({display:"inline-block"});a("#vf_top,#file_man").css({display:"block"});a("#preview_img").remove()});a(".act_pre .insert.avai").live("click",function(){var b=""+window.location;if(-1!=b.indexOf("opener=plugin")){var c=a("#preview .act_pre .download").attr("href");if(c){var g=
tinyMCEPopup.getWindowArg("window");g.document.getElementById(tinyMCEPopup.getWindowArg("input")).value=c;"undefined"!=typeof g.ImageDialog&&(g.ImageDialog.getImageData&&g.ImageDialog.getImageData(),g.ImageDialog.showPreviewImage&&g.ImageDialog.showPreviewImage(c))}tinyMCEPopup.close()}if(-1!=b.indexOf("opener=editor")){var e="",b=0;0<a("#preview .img img").length&&(e='<img src="'+a("#preview .act_pre .download").attr("href")+'" alt="" />',b=1);0<a("#preview .img .movie").length&&(b=a("#preview .act_pre .download").attr("href"),
e='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="440" height="330"><param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.7.swf" /><param name="flashvars" value=\'config={"clip":{"url":"'+b+'","autoPlay":false}}\' /> <embed type="application/x-shockwave-flash" width="440" height="330" src="http://releases.flowplayer.org/swf/flowplayer-3.2.7.swf"flashvars=\'config={"clip":{"url":"'+b+'","autoPlay":false}}\'/></object>',b=1);if(0<a("#preview #screen_flash #mymovie").length){var h=
320,j=240;a.post(d.url+"size&folder="+folder+"&filename="+a("#preview #screen_flash").attr("title"),function(b){b=a.parseJSON(b);b.result&&(h=b.result[0],j=b.result[1],b=a("#preview #screen_flash #mymovie").attr("src"),e='<object width="'+h+'" height="'+j+'" data="'+b+'" type="application/x-shockwave-flash"><param name="src" value="'+b+'" /></object>',0<e.length&&(tinyMCEPopup.editor.execCommand("mceInsertContent",!1,e,{skip_undo:1}),tinyMCEPopup.editor.execCommand("mceRepaint"),tinyMCEPopup.editor.focus(),
tinyMCEPopup.close()))})}0<a("#preview .img .unknown").length&&(e='<a href="'+folder+a("#preview .img .unknown").attr("title")+'">'+a("#preview .img .unknown").attr("title")+"</a>",b=1);0<e.length&&1==b&&(tinyMCEPopup.editor.execCommand("mceInsertContent",!1,e,{skip_undo:1}),tinyMCEPopup.editor.execCommand("mceRepaint"),tinyMCEPopup.editor.focus(),tinyMCEPopup.close())}});a("#cmd .insert").live("click",function(){if(0<a(".f_list .selected").length){var b="",c=a(".f_list .selected").length;a(".f_list .selected").each(function(){var g=
a("a",this).attr("title"),e=g.substring(g.lastIndexOf(".")+1,g.length).toLowerCase();if(-1!=a.inArray(e,["jpg","jpeg","png","gif"]))b+='<img src="'+d.upload+folder+g+'" alt="" />',c--;else if(-1!=a.inArray(e,["swf"])){var h=320,j=180;a.post(d.url+"size&folder="+folder+"&filename="+a(".filename",this).attr("title"),function(d){d=a.parseJSON(d);d.result&&(h=d.result[0],j=d.result[1],b+='<object width="'+h+'" height="'+j+'" data="'+folder+g+'" type="application/x-shockwave-flash"><param name="src" value="'+
folder+g+'" /></object>',c--,0==c&&(tinyMCEPopup.editor.execCommand("mceInsertContent",!1,b,{skip_undo:1}),tinyMCEPopup.editor.execCommand("mceRepaint"),tinyMCEPopup.editor.focus(),tinyMCEPopup.close()))})}else b=-1!=a.inArray(e,["flv"])?b+('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="440" height="330"><param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.7.swf" /><param name="flashvars" value=\'config={"clip":{"url":"'+d.upload+folder+g+'","autoPlay":false}}\' /> <embed type="application/x-shockwave-flash" width="440" height="330" src="http://releases.flowplayer.org/swf/flowplayer-3.2.7.swf"flashvars=\'config={"clip":{"url":"'+
d.upload+folder+g+'","autoPlay":false}}\'/></object>'):b+('<a href="'+folder+g+'">'+g+"</a>"),c--});0==c&&(tinyMCEPopup.editor.execCommand("mceInsertContent",!1,b,{skip_undo:1}),tinyMCEPopup.editor.execCommand("mceRepaint"),tinyMCEPopup.editor.focus(),tinyMCEPopup.close())}})}})(jQuery);

/* Free table head */
function UpdateTableHeaders(){$("div.tablefile").each(function(){mtop=0<location.href.indexOf("quickview")?0:31;var a=$(".tableFloatingHeaderOriginal",this),b=$(".tableFloatingHeader",this),c=$(this).offset(),d=$(window).scrollTop();d>c.top-mtop&&(d<c.top+$(this).height())-mtop?(b.css("visibility","visible"),$("td",b).each(function(b){b=$("td",a).eq(b).css("width");$(this).css("width",b)}),b.css("width",$(this).css("width"))):(b.css("visibility","hidden"),b.css("top",mtop+"px"))})}
$(function(){$.browser.msie||(scroll_fileman=function(){0<location.href.indexOf("quickview")?(mtop=0,$("#tree").css({height:"175px"})):mtop=31;$("table.tablefile").each(function(){$(this).wrap('<div class="tablefile" style="position:relative"></div>');var b=$("tr:first",this);b.before(b.clone());var a=$("tr:first",this);a.addClass("tableFloatingHeader");a.css("position","fixed");a.css("top",mtop+"px");a.css("visibility","hidden");b.addClass("tableFloatingHeaderOriginal")});UpdateTableHeaders();$(window).scroll(UpdateTableHeaders);
$(window).resize(UpdateTableHeaders);scrollY=0;0<$("#cmd").length&&(cmd_init(),$(window).scroll(function(){scrollY=$.browser.safari?$("body").scrollTop():$("body,html,document").scrollTop();vf_cmdscroll(mtop)}),$(window).resize(function(){returnTop(0);cmd_init()}));0<$(".f_folders_scroll").length&&(folder_left_init(),$(window).scroll(function(){scrollY=$.browser.safari?$("body").scrollTop():$("body,html,document").scrollTop();vf_folder_leftscroll(mtop)}),$(window).resize(function(){returnTop(0);folder_left_init()}));
var a=0,a=$(window).height()-$(".f_folders_scroll").offset().top-175-30;$("#tree").css({height:a});$(".f_folders").css({height:$(".f_folders_scroll").height()});$(window).resize(function(){a=$(window).height()-$(".f_folders_scroll").offset().top-175-30;$("#tree").css({height:a});$(".f_folders").css({height:$(".f_folders_scroll").height()})})})});function cmd_init(){s_cmd_top=$("#cmd").offset().top;$("#cmd").css({position:"relative",top:0}).removeClass("cmd_scroll");cmdpos_flag=0;vf_cmdscroll()}
function vf_cmdscroll(a){scrollY>s_cmd_top-a?1!=cmdpos_flag&&($("#cmd").css({position:"fixed",top:a+"px"}).addClass("cmd_scroll"),cmdpos_flag=1):0!=cmdpos_flag&&($("#cmd").css({position:"relative",top:0}).removeClass("cmd_scroll"),cmdpos_flag=0)}function folder_left_init(){s_folder_top=$(".f_folders_scroll").offset().top;$(".f_folders").css({height:$(".f_folders_scroll").height()});$(".f_folders_scroll").css({position:"relative",top:0});folder_flag=0;vf_folder_leftscroll()}
function vf_folder_leftscroll(a){scrollY>s_folder_top-(65+a)?1!=folder_flag&&($(".f_folders_scroll").css({position:"fixed",top:a+65+"px"}),folder_flag=1):0!=folder_flag&&($(".f_folders_scroll").css({position:"relative",top:0}),folder_flag=0)};

/* Scroll */
$(function(){scroll_fileman=function(){0<location.href.indexOf("quickview")?(mtop=0,$("#tree").css({height:"175px"})):mtop=31;scrollY=0;0<$("table.tablefile").length&&(1>$("#th_scroll").length&&$("table.tablefile").parent().before('<div id="th_scroll"></div>'),0<$("table.tablefile").length&&(th_scroll_init(),$(window).scroll(function(){scrollY=$.browser.safari?$("body").scrollTop():$("body,html,document").scrollTop();vf_th_scroll(mtop)})));0<$("#cmd").length&&(cmd_init(),$(window).scroll(function(){scrollY=
$.browser.safari?$("body").scrollTop():$("body,html,document").scrollTop();vf_cmdscroll(mtop)}),$(window).resize(function(){returnTop(0);cmd_init()}));0<$(".f_folders_scroll").length&&(folder_left_init(),$(window).scroll(function(){scrollY=$.browser.safari?$("body").scrollTop():$("body,html,document").scrollTop();vf_folder_leftscroll(mtop)}),$(window).resize(function(){returnTop(0);folder_left_init()}));var a=0,a=$(window).height()-$(".f_folders_scroll").offset().top-175-30;$("#tree").css({height:a});
$(".f_folders").css({height:$(".f_folders_scroll").height()});$(window).resize(function(){a=$(window).height()-$(".f_folders_scroll").offset().top-175-30;$("#tree").css({height:a});$(".f_folders").css({height:$(".f_folders_scroll").height()})})}});function vf_th_scroll(a){scrollY>s_headtable-a?1!=s_headtable_flag&&($("#th_scroll").css({display:"block",top:a+"px"}),s_headtable_flag=1):0!=s_headtable_flag&&($("#th_scroll").css({display:"none",top:"0"}),s_headtable_flag=0)}
$.fn.table_width_init=function(){for(var a=$("thead td",this).length,b=1;b<a;b++)$("thead tr td:eq("+b+")",this).css({width:$("thead tr td:eq("+b+")",this).width()})};function th_scroll_init(){$("table.tablefile").table_width_init();var a=$("table.tablefile").width()+2;$("#th_scroll").css({width:a});a=$("table.tablefile thead tr").html().replace(/<td/gi,"<div").replace(/td>/gi,"div>");$("#th_scroll").html(a);s_headtable=$("table.tablefile").offset().top;s_headtable_flag=0;vf_th_scroll()}
function cmd_init(){s_cmd_top=$("#cmd").offset().top;$("#cmd").css({position:"relative",top:0}).removeClass("cmd_scroll");cmdpos_flag=0;vf_cmdscroll()}function vf_cmdscroll(a){scrollY>s_cmd_top-a?1!=cmdpos_flag&&($("#cmd").css({position:"fixed",top:a+"px"}).addClass("cmd_scroll"),cmdpos_flag=1):0!=cmdpos_flag&&($("#cmd").css({position:"relative",top:0}).removeClass("cmd_scroll"),cmdpos_flag=0)}
function folder_left_init(){s_folder_top=$(".f_folders_scroll").offset().top;$(".f_folders").css({height:$(".f_folders_scroll").height()});$(".f_folders_scroll").css({position:"relative",top:0});folder_flag=0;vf_folder_leftscroll()}function vf_folder_leftscroll(a){scrollY>s_folder_top-(65+a)?1!=folder_flag&&($(".f_folders_scroll").css({position:"fixed",top:a+65+"px"}),folder_flag=1):0!=folder_flag&&($(".f_folders_scroll").css({position:"relative",top:0}),folder_flag=0)};