<?php
/**
* @version		$Id: banners.php 3 2012-08-22 13:39 phu $
* @package		vFramework.cp.banners
* @copyright	(C) 2012 Vipcom. All rights reserved.
* @license		Commercial
*/
defined('V_LIFE')or die('v');$cfg['file']['dir']='b';$tpl->lang('banner');$banners_cfg=array('structure'=>'id:int,pid:int,title:string,tip:string,note:string,imageurl:image,width:int,height:int,clickurl:string,clicks:int,impressions:int,ordering:int,created:timestamp,modified:timestamp,published:timestamp','langs'=>0,'task'=>array('index'=>array('type'=>4,'auth'=>'access','cmd'=>'create,delete,publish','filter'=>'search','field'=>'id,title,clicks,impressions,ordering,published','render'=>'title,clicks,impressions,ordering',),'edit'=>array('type'=>12,'auth'=>'edit','notnull'=>'title','field'=>'title,imageurl,width,height,clickurl,tip,note',),'view'=>array('type'=>1,'auth'=>'access','field'=>'title,imageurl,width,height,clickurl,tip,note',),'delete'=>array('type'=>11,'auth'=>'delete','ret'=>'',),'publish'=>array('type'=>21,'field'=>'published','auth'=>'publish','ret'=>'',),'order'=>array('type'=>22,'auth'=>'move','field'=>'id','ret'=>'',),'resync'=>array('type'=>23,'field'=>'id,ordering',),'reset'=>array('auth'=>'delete',)));
class Banners extends vCPController{public function __construct(){$this->model=new BannersModel();parent::__construct();$db=vDatabase::instance();$s='SELECT title FROM #__banner WHERE id='.vPage::alt('section');if(!$db->query($s))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows())cpPage::nav($db->fetch_field('title'),$this->cfg['url']);else vPage::redirect(VAR_INDEX.'?'.VAR_LANG.'='.vPage::alt('lang').'&'.VAR_PAGE.'=cp.banner');}public function index_task(){parent::task();$tpl=vTemplate::instance();$stf=vStaff::instance();if($stf->admin)vPage::head('$(function() {
$(".th_clicks").append(\' <a href="'.$this->cfg['url'].'&'.VAR_TASK.'=reset&'.VAR_ACTION.'=c"><span class="ico ireset" title="'.$tpl->_('Reset').'"></span></a>\');
$(".th_impressions").append(\' <a href="'.$this->cfg['url'].'&'.VAR_TASK.'=reset&'.VAR_ACTION.'=i"><span class="ico ireset" title="'.$tpl->_('Reset').'"></span></a>\');
})','script');}protected function submit($d){global $alt,$db;$d['pid']=vPage::alt('section');$t='';if($d['width']==0||$d['height']==0){if(isset($d['imageurl'])&&$d['imageurl'])$t=$d['imageurl'];else if($d['id']&&!$alt['_']['saveas']){$s='SELECT imageurl FROM #__banners WHERE id='.$d['id'];if(!$db->query($s))trigger_error($db->error(),E_USER_ERROR);$t=$db->fetch_field('imageurl');}if($t){$t=@getimagesize(PATH_UPLOAD.DS.$t);if($t)vForm::_size($d['width'],$d['height'],$t[0],$t[1]);else{$d['width']=0;$d['height']=0;}}else{$d['width']=0;$d['height']=0;}}return parent::submit($d);}public function reset_task(){$db=vDatabase::instance();$s='UPDATE #__banners SET '.((vPage::alt('action')=='i')?'impressions':'clicks').'=0 WHERE pid='.vPage::alt('section');if(!$db->query($s))trigger_error($db->error(),E_USER_ERROR);$this->ret=1;}public function view_data($d){$d['imageurl']=vForm::media($d['imageurl'],array('width'=>$d['width'],'height'=>$d['height']),false);return $d;}public function resync_task(){parent::task();include PATH_WORKING.DS.'group_model.php';GroupModel::resync();}}
class BannersModel extends vCPModel{protected function records_sql($a=0){$s=parent::records_sql($a);$s['w'].=' AND a.pid='.vPage::alt('section');return $s;}}$ctrl=new Banners();$ctrl->exec();unset($ctrl);