<?php
defined('V_LIFE')or die('v');
class vStaff extends vSession{private static $_s;var $profile=array();var $access=0;var $edit=0;var $delete=0;var $create=0;var $publish=0;var $move=0;var $own=0;var $manage=0;var $admin=0;var $perm=array('access'=>0,'create'=>0,'edit'=>0,'delete'=>0,'publish'=>0,'move'=>0,'own'=>0,'manage'=>0);public static function instance(){if(is_null(self::$_s))self::$_s=new self();return self::$_s;}function __construct(){global $cfg,$db,$alt;$this->session('start');$sid=$this->sid();if($sid){$sql='SELECT id,username,level,lang,email,prop,ip,log_expire,log_time FROM #__staff
				WHERE enabled=1 AND log_sid="'.$sid.'" AND log_expire>='.time();if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows()){$this->profile=$db->fetch_row();$this->profile['prop']=vRegistry::parse($this->profile['prop'],1);if(isset($this->profile['prop']['page']))$this->profile['prop']['page']=','.$this->profile['prop']['page'].',';if(V_CP>1){$db->query('SELECT a.firstname,a.lastname,a.email,b.code FROM #__hr a LEFT JOIN #__position b ON a.pos=b.id WHERE a.enabled=1 AND a.sid='.$this->profile['id'],1);$t=$db->fetch_row();$this->profile['firstname']=$t['firstname'];$this->profile['lastname']=$t['lastname'];$this->profile['code']=$t['code'];if(!$this->profile['email'])$this->profile['email']=$t['email'];unset($t);}$sql='UPDATE #__staff
					SET log_expire='.(time()+ $cfg['session_lifetime']).'
					WHERE log_sid="'.$sid.'"';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);$this->state='active';}}if($this->perm=$this->auth($alt['page'])){$this->access=$this->perm['access'];$this->edit=$this->perm['edit'];$this->delete=$this->perm['delete'];$this->create=$this->perm['create'];$this->publish=$this->perm['publish'];$this->move=$this->perm['move'];$this->own=$this->perm['own'];$this->manage=$this->perm['manage'];$this->admin=$this->perm['admin'];}}function login($user,$pass){global $cfg,$db;if($user AND $pass){$sql='SELECT id, password FROM #__staff
				WHERE username="'.$user.'" AND enabled=1';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows()){$d=$db->fetch_row();if($d['password']==md5($pass)){$x['log_time']=time();$x['log_expire']=$x['log_time'] + $cfg['session_lifetime'];$x['log_sid']=md5(uniqid($d['id'].$d['password'].$x['log_time']));$x['ip']=vRequest::ip();$sql=$db->sql('UPDATE','#__staff',$x,'id='.$d['id']);if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);$this->sid($x['log_sid']);$this->state='active';return true;}}}return false;}function logout(){global $db;$this->state=null;$sid=$this->sid();if($sid){$sql='UPDATE #__staff
				SET log_expire=0, log_sid=""
				WHERE log_sid="'.$sid.'"';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows()){setcookie('webadmin',0,time()- 60,'/');$this->session('clear','sid.cp');return true;}}return false;}function auth($func='',$right=''){global $db,$map;if($func AND $this->state=='active'){if($this->profile['level'])return($right)?1:array('access'=>1,'edit'=>1,'delete'=>1,'create'=>1,'publish'=>1,'move'=>1,'own'=>1,'manage'=>1,'admin'=>1);$t=array('access'=>0,'create'=>0,'edit'=>0,'delete'=>0,'publish'=>0,'move'=>0,'own'=>0,'manage'=>0);if(isset($map->i[$func]))$func=$map->i[$func]['alias'];$a=0;if(isset($this->profile['prop']['adv'])&&isset($this->profile['prop']['adv'][$func])){$a=$this->profile['prop']['adv'][$func];}else if(isset($this->profile['prop']['page'])&&isset($this->profile['prop']['auth'])&&strpos($this->profile['prop']['page'],','.$func.',')!==false){$a=$this->profile['prop']['auth'];}if($a){$sql='SELECT prop FROM #__staff_grp WHERE id='.$a;if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows())$t=array_merge($t,vRegistry::parse($db->fetch_field('prop')));}$t['admin']=0;return($right)?$t[$right]:$t;}return false;}function keepalive(){global $cfg;$t='<script type="text/javascript">
function keepalive(){
  $.ajax({url:"'.VAR_INDEX.'?'.VAR_PAGE.'=cp.staff&'.VAR_TASK.'=keepalive",context:document.body,success:function(){}});
}
var holdTheInterval = setInterval(keepalive, '.(5*60*1000).');
</script>';vPage::head($t);return;}function code(){foreach(func_get_args()as $e){if(strpos($this->profile['code'],','.$e.',')!==false){return 1;}}return 0;}function revs($c,$i,$d=0){global $db;if($d==0){$db->query('SELECT count(id) as count FROM #__staff_revs WHERE ctype="'.$c.'" AND rid='.$i);return $db->fetch_field('count');}else if($d===true){$db->query('SELECT * FROM #__staff_revs WHERE ctype="'.$c.'" AND rid='.$i);return $db->fetch();}else if($d){$o=implode(',',array_keys($d));$db->query('SELECT '.$o.' FROM #__'.$c.' WHERE id='.$i,1);$o=$db->fetch_row();if($o=array_diff($o,$d)){$db->query('INSERT INTO #__staff_revs (rid, ctype, prop, stf, modified) VALUES ('.$i.', "'.$c.'", "'.vRegistry::ini($o).'", '.$this->profile['id'].', '.time().')');return 1;}return 0;}}function logs($p,$t='',$e=array()){global $db;$d=array('staff'=>(isset($this->profile['id'])&&$this->profile['id'])?$this->profile['id']:-1,'page'=>$p,'task'=>$t,'prop'=>vRegistry::ini($e),'created'=>time(),);$s=$db->sql('INSERT','#__staff_logs',$d);if(!$db->query($s))trigger_error($db->error(),E_USER_ERROR);}function get(){global $db;$a=array();$sql='SELECT id, username FROM #__staff WHERE enabled=1';if(!$db->query($sql))trigger_error($db->error(),E_USER_ERROR);if($db->affected_rows()){foreach($db->fetch()as $v)$a[$v['id']]=$v['username'];}return $a;}}