<?php
/**
* @version		$Id: blocks.php 3 2013-12-30 14:07 phu $
* @package		vFramework.cp.blocks
* @copyright	(C) 2012 Vipcom. All rights reserved.
* @license		Commercial
*/
defined('V_LIFE')or die('v');$blocks_cfg=array('structure'=>'id:int,sid:int,lang,title:string,ctype:ctype,pos,page:pages,auth:int,prop:prop,ordering:int,enabled:int','langs'=>1,'task'=>array('index'=>array('type'=>4,'auth'=>'access','cmd'=>'create,delete,publish,imexport','filter'=>'search,publish,pos','field'=>'id,lang,title,ctype,pos,page,ordering,enabled','render'=>'title,ctype,pos,page,ordering',),'edit'=>array('type'=>12,'auth'=>'edit','field'=>'id,lang,title,ctype,pos,auth,ordering,page,prop,enabled','render'=>'lang,title,ctype,pos,ordering,page','render2'=>'prop','notnull'=>'title',),'prop'=>array(),'order'=>array('auth'=>'move','type'=>22,),'resync'=>array('type'=>23,'field'=>'id,ordering',),'delete'=>array('type'=>11,'auth'=>'delete','ret'=>'',),'publish'=>array('type'=>21,'field'=>'enabled','auth'=>'publish','ret'=>'',),'imexport'=>array('type'=>31,'field'=>'id,lang,title,ctype,pos,page,auth,prop,ordering','auth'=>'admin','paging'=>9999,),),);
class Blocks extends vCPController{public function __construct(){global $tpl,$cfg;$this->model=new BlocksModel();$this->view=new BlocksView();parent::__construct();$p=DEF_POS;$l=null;$t=PATH_THEME.DS.'theme.ini';if(is_file($t)){$t=vRegistry::parse(file_get_contents($t),1);if(isset($t['lang_'.$cfg['cp']['lang']]))$l=$t['lang_'.$cfg['cp']['lang']];else if(isset($t['lang']))$l=$t['lang'];if(!isset($cfg['theme_style']))$cfg['theme_style']='';$k=1;while(isset($t[$k])){if($cfg['theme_page']==$t[$k]['tpl']&&$cfg['theme_style']==$t[$k]['css']&&isset($t[$k]['pos'])&&$t[$k]['pos']){$p=$t[$k]['pos'];break;}$k++;}}foreach(explode(',',$p)as $k)$this->cfg['pos'][$k]=isset($l[$k])?$l[$k]:(isset($tpl->l['POS_'.$k])?$tpl->l['POS_'.$k]:$k);$this->cfg['auth']=array(0=>$tpl->l['MEMBER'].' + '.$tpl->l['GUEST'],-1=>$tpl->l['GUEST'],1=>$tpl->l['MEMBER']);cpPage::html('<div id="locmap"><img src="'.URL_THEME.'map.jpg" alt="L_MAP" /></div>');}protected function index_data($d=null){global $ctype,$map,$tpl;$d=parent::data($d);for($i=0,$n=count($d);$i<$n;$i++){$v=&$d[$i];$v['U_VIEW']='';if(isset($ctype->r[1][$v['ctype']])&&$ctype->r[1][$v['ctype']]['func']){$v['ctype']='<a href="'.VAR_INDEX.'?'.VAR_PAGE.'=cp.'.$v['ctype'].'">'.$v['ctype'].'<span class="ico iposts"></span></a>';}$a=explode(',',$v['page']);$v['page']=array();foreach($a as $b)if($b){if(isset($map->i[$b])){$v['page'][]='<a href="'.$this->cfg['url'].'&amp;filter[page]='.$b.'">'.$map->i[$b]['title'].'</a>';}}$v['page']=($v['page'])?implode(', ',$v['page']):'<a href="'.$this->cfg['url'].'">'.$tpl->l['ALL'].'</a>';if(isset($this->cfg['pos'][$v['pos']])){$v['pos']='<a href="'.$this->cfg['url'].'&amp;filter[pos]='.$v['pos'].'">'.$this->cfg['pos'][$v['pos']].'</a>';}}return $d;}protected function edit_data($d=0){global $cfg,$tpl,$map;if(!$d)$d=array('ctype'=>'html','lang'=>'','enabled'=>1,'page'=>'','auth'=>0,'pos'=>'','prop'=>null);$d['pos']=vForm::select($this->cfg['pos'],'pos','','','',$d['pos']).' <a rel="locmap" class="tooltip" href="javascript:void(0)"><span class="ico imap"></span></a>';if($map->m){$this->cfg['task']['edit']['render'][]='auth';$d['auth']=vForm::select($this->cfg['auth'],'auth','','','',$d['auth']);}return parent::data($d);}protected function request(){global $map;if($map->m)$this->cfg['task']['edit']['field'][]='auth';$x=parent::request();$x['page']=($x['page'])?','.$x['page'].',':'';if(vRequest::bool('showtitle')===false&&$x['title']&&$x['title']{0}!='~')$x['title']='~'.$x['title'];if(V_LIFE==2&&!isset($x['sid']))$x['sid']=V_SITE;return $x;}}
class BlocksModel extends vCPModel{protected function records_sql($a=0){$s=parent::records_sql();$t=vPage::alt('filter.page');if($t)$s['w'].=' AND (a.page="" OR a.page LIKE "%,'.$t.',%")';if(V_LIFE==2)$s['w'].=' AND a.sid='.V_SITE;return $s;}protected function erecords_sql($a=0,$b=0,$r=1){$s=parent::erecords_sql($a,$b,$r);if(V_LIFE==2)$s[0]['w'].=' AND sid='.V_SITE;return $s;}}
class BlocksView extends vCPView{public function index_render($d=null,$c=0){global $map;parent::render($d,$c);cpPage::filter('pos',$this->cfg['pos'],false);cpPage::filter('page',$map->select(),false);vPage::head('.th_page{width:40%}','style');vPage::head('$(function(){$(".th_pos").append(\' <a rel="locmap" class="tooltip" href="javascript:void(0)"><span class="ico imap"></span></a>\');});','script');}public function edit_render($d=null){parent::render($d);$tpl=vTemplate::instance();$t=0;if(isset($d['title'])&&$d['title']&&$d['title']{0}=='~'){$d['title']=substr($d['title'],1);$t=1;}vPage::head('<script type="text/javascript">$(function(){
$("#title").parent().append(\'<input type="checkbox" name="showtitle" id="showtitle" value="1" '.(($t)?'':'checked="checked" ').'/><label for="showtitle">'.$tpl->l['SHOW'].'</label>\');
$("input#ordering").parent().parent().hide();
});</script>');}}$ctrl=new Blocks();$ctrl->exec();unset($ctrl);?>